---
sidebar: sidebar 
permalink: concept_cs_event_rate_checker.html 
summary: 在安裝ONTAP SVM DSC 之前，可以執行此腳本來檢查 SVM 中的事件速率 
keywords: event, checker, rate, sizing, cloud secure 
---
= SVM 事件率檢查器（代理程式規模指南）
:hardbreaks:
:allow-uri-read: 


[role="lead"]
事件速率檢查器用於在安裝ONTAP SVM 資料收集器之前檢查 SVM 中的 NFS/SMB 組合事件速率，以查看一台代理機器能夠監控多少個 SVM。使用事件率檢查器作為規模指南來幫助規劃您的安全環境。

一個代理程式最多可以支援 50 個資料收集器。



== 要求：

* 集群 IP
* 叢集管理員使用者名稱和密碼



NOTE: 執行此腳本時，不應為正在確定事件率的 SVM 執行ONTAP SVM 資料收集器。

步驟：

. 請依照 CloudSecure 中的說明安裝代理程式。
. 安裝代理程式後，以 sudo 使用者身分執行 _server_data_rate_checker.sh_ 腳本：
+
 /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
. 該腳本需要在 Linux 機器上安裝 _sshpass_。有兩種安裝方法：
+
.. 運行以下命令：
+
 linux_prompt> yum install sshpass
.. 如果這不起作用，則從網路下載 _sshpass_ 到 Linux 機器並執行以下命令：
+
 linux_prompt> rpm -i sshpass


. 出現提示時提供正確的值。請參閱下面的範例。
. 該腳本大約需要 5 分鐘才能運行。
. 運行完成後，腳本將從 SVM 列印事件率。您可以在控制台輸出中檢查每個 SVM 的事件率：
+
 “Svm svm_rate is generating 100 events/sec”.


每個 Ontap SVM 資料收集器可以與單一 SVM 關聯，這表示每個資料收集器將能夠接收單一 SVM 產生的事件數量。

請記住以下幾點：

A) 使用此表格作為一般尺寸指南。您可以增加核心和/或記憶體的數量來增加支援的資料收集器的數量，最多可增加 50 個資料收集器：

|===


| 代理機器配置 | SVM 資料收集器的數量 | 代理機器可以處理的最大事件速率 


| 4核，16GB | 10名資料收集員 | 20K 事件/秒 


| 4核，32GB | 20名資料收集員 | 20K 事件/秒 
|===
B) 若要計算總事件數，請將該代理人的所有 SVM 產生的事件數相加。

C) 如果腳本不在高峰時段運行，或者高峰流量難以預測，則保持 30% 的事件率緩衝。

B+C應該小於A，否則Agent機器會監控失敗。

也就是說，單一代理機器上可以新增的資料採集器數量應遵循以下公式：

 Sum of all Event rate of all Data Source Collectors + Buffer Event rate of 30% < 20000 events/second
查看link:concept_cs_agent_requirements.html["代理要求"]頁面以了解其他先決條件和要求。



== 例子

假設我們有三個 SVMS，分別每秒產生 100、200 和 300 個事件。

我們應用公式：

....
 (100+200+300) + [(100+200+300)*30%] = 600+180 = 780events/sec
780 events/second is < 20000 events/second, so the 3 SVMs can be monitored via one agent box.
....
控制台輸出在代理機器的目前工作目錄中的檔案名稱 __fpolicy_stat_<SVM Name>.log__ 中可用。

在以下情況下，腳本可能會給出錯誤的結果：

* 提供的憑證、IP 或 SVM 名稱不正確。
* 具有相同名稱、序號等的已存在 fpolicy 將會出現錯誤。
* 腳本在運行時突然停止。


範例腳本運行如下所示：

 [root@ci-cs-data agent]# /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
....
Enter the cluster ip: 10.192.139.166
Enter the username to SSH: admin
Enter the password:
Getting event rate for NFS and SMB events.
Available SVMs in the Cluster
-----------------------------
QA_SVM
Stage_SVM
Qa-fas8020
Qa-fas8020-01
Qa-fas8020-02
audit_svm
svm_rate
vs_new
vs_new2
....
....
-----------------------------
Enter [1/5] SVM name to check (press enter to skip): svm_rate
Enter [2/5] SVM name to check (press enter to skip): audit_svm
Enter [3/5] SVM name to check (press enter to skip):
Enter [4/5] SVM name to check (press enter to skip):
Enter [5/5] SVM name to check (press enter to skip):
Running check for svm svm_rate...
Running check for svm audit_svm...
Waiting 5 minutes for stat collection
Stopping sample svm_rate_sample
Stopping sample audit_svm_sample
fpolicy stats of svm svm_rate is saved in fpolicy_stat_svm_rate.log
Svm svm_rate is generating 100 SMB events/sec and 100 NFS events/sec
Overall svm svm_rate is generating 200 events/sec
fpolicy stats of svm audit_svm is saved in fpolicy_stat_audit_svm.log
Svm audit_svm is generating 200 SMB events/sec and 100 NFS events/sec
Overall svm audit_svm is generating 300 events/sec
....
 [root@ci-cs-data agent]#


== 故障排除

|===


| 問題 | 回答 


| 如果我在已配置工作負載安全的 SVM 上執行此腳本，它是否僅使用 SVM 上現有的 fpolicy 配置，還是設定臨時配置並執行該過程？ | 即使對於已經配置了工作負載安全性的 SVM，事件率檢查器也可以正常運作。應該不會有影響。 


| 我可以增加可運行該腳本的 SVM 數量嗎？ | 是的。只需編輯腳本並將 SVM 的最大數量從 5 更改為任何所需的數量。 


| 如果我增加 SVM 的數量，會增加腳本的運行時間嗎？ | 不會。即使 SVM 的數量增加，該腳本最多也會運作 5 分鐘。 


| 我可以增加可運行該腳本的 SVM 數量嗎？ | 是的。您需要編輯腳本並將 SVM 的最大數量從 5 更改為任何所需的數量。 


| 如果我增加 SVM 的數量，會增加腳本的運行時間嗎？ | 不會。即使 SVM 的數量增加，該腳本最多也會運作 5 分鐘。 


| 如果我使用現有代理程式運行事件率檢查器會發生什麼情況？ | 針對已存在的代理程式運行事件率檢查器可能會導致 SVM 上的延遲增加。當事件率檢查器運作時，這種增加將是暫時的。 
|===