---
sidebar: sidebar 
permalink: concept_import_from_dashboard_gallery.html 
summary: 您可以匯入建議的儀表板來幫助回答業務洞察問題。您也可以匯入先前匯出的自訂儀表板。 
keywords: dashboard, gallery, import, export 
---
= 導入儀表板
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Data Infrastructure Insights提供了許多推薦的儀表板，為您的數據提供業務洞察。每個儀表板都包含旨在幫助回答特定問題或解決與目前在租戶上收集的數據相關的特定問題的小部件。DII 還允許您匯出有用的儀表板並將其匯入到另一個租戶。



== 從儀表板庫導入

若要從庫中匯入儀表板，請執行下列操作：

. 選擇“可觀察性”>“探索”>“所有儀表板”*
. 點擊“+導入儀表板”並選擇“從圖庫導入”。
+
根據您環境中的資料收集器，顯示「建議的儀表板」清單。儀表板可協助解答不同類型物件的問題，包括 AWS、 NetApp、儲存、VMware 等。

. 從清單中選擇一個或多個儀表板，然後按一下「新增儀表板」。這些儀表板將顯示在您的儀表板清單中。


除了建議的儀表板之外，您還可以選擇匯入與目前資料無關的*附加儀表板*。例如，如果您目前沒有安裝儲存資料收集器，但計劃在將來配置一些，您仍然可以選擇匯入與儲存相關的儀表板。這些儀表板將可供顯示，但在配置至少一個儲存資料收集器之前可能不會顯示任何相關資料。

具有管理員或帳戶擁有者角色的使用者可以從儀表板庫匯入。



== 導入已匯出的儀表板

若要*匯出*儀表板，請在*可觀察性 > 探索 > 所有儀表板*頁面上，按一下儀表板右側的選單並選擇_匯出_。您也可以選擇多個儀表板，然後從「批次操作」下拉式選單中選擇「匯出」。儀表板保存在本機系統上的 .ZIP 檔案中。

若要*匯入*儀表板，請導覽至所需的租用戶並執行下列操作：

. 選擇“可觀察性”>“探索”>“所有儀表板”*
. 點擊“*+導入儀表板*”並選擇“從檔案導入”。選擇您先前匯出的檔案的 .ZIP。儀表板將被匯入並顯示在您的儀表板清單中。請注意，如果您匯入的儀表板與現有儀表板同名，儀表板名稱後面會附加「(2)」。

