---
sidebar: sidebar 
permalink: concept_asset_user_data_section.html 
summary: 資產頁面的使用者資料部分可讓您為目前資產指派註釋或應用程式。 
keywords: asset page, user data, applications, annotations 
---
= 用戶資料部分
:hardbreaks:
:allow-uri-read: 


[role="lead"]
資產頁面的使用者資料部分顯示並允許您更改任何使用者定義的數據，例如應用程式和註釋。



== 使用用戶資料部分分配或修改應用程式

您可以將租用戶上執行的應用程式指派給某些資產（主機、虛擬機器、磁碟區、內部磁碟區、qtree 和虛擬機器管理程式）。使用者資料部分可讓您新增、變更或刪除指派給資產的應用程式。對於除卷之外的所有這些資產類型，您可以指派多個應用程式。

.步驟
. 透過執行下列任一操作來找到資產頁面：
+
.. 查詢資產列表，然後從列表中選擇一個。
.. 在儀表板上，找到資產名稱並按一下它。
.. 執行搜尋並從結果中選擇一項資產。
+
資產頁面顯示。該頁面的使用者資料部分顯示目前指派的應用程式或註釋。





若要變更已指派的應用程序，或指派一個或多個應用程序，請下拉「應用程式」清單並選擇要指派給資產的應用程式。您可以鍵入內容來搜尋應用程序，或從清單中選擇一個。

若要刪除應用程序，請下拉應用程式清單並取消選取該應用程式。



== 使用使用者資料部分分配或修改註釋

當客製化Data Infrastructure Insights以追蹤公司需求的資料時，您可以定義稱為註釋的專門註釋，並將其分配給您的資產。資產頁面的使用者資料部分顯示指派給資產的註釋，也允許您變更指派給該資產的註釋。

.步驟
. 若要為資產新增註釋，請在資產頁面的使用者資料部分中按 *+註釋*。
. 從清單中選擇一個註釋。
. 按一下“值”並根據所選註釋的類型執行以下操作之一：
+
.. 如果註釋類型是清單、日期或布林值，請從清單中選擇一個值。
.. 如果註釋類型是文本，請輸入一個值。


. 按一下「Save（儲存）」。


註釋已指派給資產。您稍後可以使用查詢按註釋過濾資產。

如果要在分配註釋後變更其值，請下拉註釋清單並輸入不同的值。

如果註解是清單類型，並且選擇了「動態新增值」選項，則除了選擇現有值之外，還可以鍵入以新增新值。
