---
sidebar: sidebar 
permalink: concept_cs_api.html 
keywords: api, access, token, swagger 
summary: 工作負載安全性包含功能強大的API、可與其他應用程式（例如CMDB）整合。 
---
= 工作負載安全API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
工作負載安全性API可讓NetApp客戶和獨立軟體廠商（ISV）將工作負載安全性與其他應用程式（例如CMDB或其他票證系統）整合。

API存取需求：

* API存取權杖模式用於授予存取權。
* API權杖管理是由具有管理員角色的工作負載安全使用者執行。




== API文件（Swagger）

登入工作負載安全性並瀏覽至*管理> API存取*、即可找到最新的API資訊。按一下「* API Documentation *（* API文件*）」連結。API文件是以Swagger為基礎、提供API的簡短說明與使用資訊、並可讓您在環境中試用。


NOTE: 如果呼叫鑑識活動 API 、請使用 cloudsecure_forensics 。 * v2* API 。如果您要對此 API 進行多個呼叫、請確定呼叫是依序進行、而非平行進行。多個平行呼叫可能會導致 API 逾時。



== API存取權杖

在使用工作負載安全性API之前、您必須先建立一個或多個* API存取權杖*。存取權杖可授予讀取權限。您也可以設定每個存取權杖的到期日。

若要建立存取權杖：

* 按一下「*管理> API存取*」
* 按一下「*+ API存取權杖*」
* 輸入* Token Name*
* 指定*權杖過期*



NOTE: 您的權杖只能在建立程序期間複製到剪貼簿並儲存。建立權杖之後、就無法擷取這些權杖、因此強烈建議您複製權杖、並將其儲存在安全的位置。系統會提示您按一下「複製API存取權杖」按鈕、然後再關閉權杖建立畫面。

您可以停用、啟用及撤銷權杖。停用的權杖可以啟用。

權杖可從客戶的觀點授予API一般用途存取權限、以管理其本身環境範圍內的API存取。

應用程式會在使用者成功驗證及授權存取後、收到存取權杖、然後在呼叫目標API時、將存取權杖作為認證。傳遞的權杖會通知API、該權杖的承載器已獲授權存取API、並根據授權期間授予的範圍執行特定動作。

傳遞存取權杖的HTTP標頭為* X-CloudInsights：Apikes*

例如、使用下列項目來擷取儲存資產：

 curl https://<tenant_host_name>/rest/v1/cloudsecure/activities -H 'X-CloudInsights-ApiKey: <API_Access_Token>'
其中、_<API_Access_Token >>是您在API存取金鑰建立期間所儲存的權杖。

如需詳細資訊、請參閱「*管理> API存取*」下的「_API文件_」連結。



== 透過 API 擷取資料的指令碼

工作負載安全代理程式包含匯出指令碼、可將要求的時間範圍分成較小的批次、以利平行呼叫 v2 API 。

指令碼位於： __/opt/oracle/cloudsecure/agent/export NetApp -script_ 。同一目錄中的 README 檔案提供使用說明。

以下是呼叫指令碼的範例命令：

[source]
----
python3 data-export.py --tenant_url <tenant id>.cs01.cloudinsights.netapp.com --access_key %ACCESS_KEY% --path_filter "<dir path>" --user_name "<user>" --from_time "01-08-2024 00:00:00" --to_time "31-08-2024 23:59:59" --iteration_interval 12 --num_workers 3
----
主要參數： - `--iteration_interval 12`：將所要求的時間範圍分成 12 小時的間隔。- `--num_workers 3`：使用 3 個執行緒平行擷取這些時間間隔。
