---
sidebar: sidebar 
permalink: concept_cs_api.html 
keywords: api, access, token, swagger 
summary: 透過 REST API 存取工作負載安全數據，並採用基於令牌的安全性身份驗證，以便與 CMDB、工單系統和其他企業應用程式整合。 
---
= 工作負載安全 API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
利用受安全性令牌認證保護的 REST API，將 Workload Security 整合到您的企業生態系統中。您可以檢索取證活動資料、管理 API 存取令牌，並與 CMDB、工單系統和其他應用程式開發自訂整合。互動式 Swagger 文件提供完整的 API 規範，並允許您直接測試端點。

API 存取要求：

* API 存取令牌模型用於授予存取權限。
* API 令牌管理由具有管理員角色的工作負載安全使用者執行。




== API 文件（Swagger）

透過登入 Workload Security 並導覽至 *Admin > API Access* 可以找到最新的 API 資訊。按一下*API 文件*連結。  API 文件基於 Swagger，提供 API 的簡要描述和使用信息，並允許您在租戶上試用。


NOTE: 如果呼叫取證活動 API，請使用 cloudsecure_forensics.activities.*v2* API。如果您要多次呼叫此 API，請確保呼叫按順序進行，而不是並行。多次並行呼叫可能會導致 API 逾時。



== API 存取令牌

在使用工作負載安全 API 之前，您必須建立一個或多個 *API 存取權杖*。存取令牌授予讀取權限。您也可以設定每個存取令牌的有效期。

若要建立存取權杖：

* 點選“管理”>“API 存取”
* 點選*+API 存取權令牌*
* 輸入*代幣名稱*
* 指定*令牌到期*



NOTE: 您的令牌僅可在建立過程中複製到剪貼簿並儲存。令牌一旦創建就無法檢索，因此強烈建議複製令牌並將其保存在安全的位置。系統將提示您按一下「複製 API 存取權杖」按鈕，然後才能關閉令牌建立畫面。

您可以停用、啟用和撤銷令牌。已禁用的令牌可以啟用。

令牌從客戶的角度授予對 API 的通用存取權限，管理其自身租用戶範圍內對 API 的存取。

使用者成功驗證並授權存取後，應用程式將收到存取令牌，然後在呼叫目標 API 時將存取令牌作為憑證傳遞。傳遞的令牌通知 API，令牌持有者已被授權存取 API 並根據授權期間授予的範圍執行特定操作。

傳遞存取令牌的 HTTP 標頭是 *X-CloudInsights-ApiKey:*

例如，使用以下命令檢索儲存資產：

 curl https://<Workload Security tenant>/rest/v1/cloudsecure/activities -H 'X-CloudInsights-ApiKey: <API_Access_Token>'
其中 _<API_Access_Token>_ 是您在建立 API 存取金鑰期間所儲存的令牌，而 _<Workload Security Tenant>_ 是您的 Workload Security 環境的租用戶 URL。

詳細資訊可以在*管理 > API 存取*下的_API 文件_連結中找到。



== 透過 API 提取資料的腳本

工作負載安全代理程式包括一個匯出腳本，透過將請求的時間範圍劃分為更小的批次來促進對 v2 API 的平行呼叫。

該腳本位於 _/opt/netapp/cloudsecure/agent/export-script_。同一目錄中的 README 檔案提供了使用說明。

以下是呼叫腳本的範例命令：

[source]
----
python3 data-export.py --tenant_url <Workload Security tenant> --access_key %ACCESS_KEY% --path_filter "<dir path>" --user_name "<user>" --from_time "01-08-2024 00:00:00" --to_time "31-08-2024 23:59:59" --iteration_interval 12 --num_workers 3
----
關鍵參數：- `--iteration_interval 12` ：將請求的時間範圍分成 12 小時的間隔。  - `--num_workers 3` ：使用 3 個執行緒並行取得這些間隔。
