---
sidebar: sidebar 
permalink: concept_searching_assets.html 
summary: 高級搜尋技術可以幫助您找到您正在尋找的資產。 
keywords: asset page, objects, search, advanced, alerts 
---
= 搜尋資產和警報的提示和技巧
:hardbreaks:
:allow-uri-read: 


[role="lead"]
可以使用多種搜尋技術來搜尋監控環境中的資料或物件。

* *通配符搜尋*
+
您可以使用 * 字元執行多字元通配符搜尋。例如，_applic*n_ 將傳回 _application_。

* *搜尋中使用的短語*
+
短語是一組用雙引號括起來的單字；例如「VNX LUN 5」。您可以使用雙引號來搜尋名稱或屬性中包含空格的文件。

* 布林運算符
+
使用布林運算符 OR、AND 和 NOT，您可以組合多個術語以形成更複雜的查詢。

+
或者

+
OR 運算子是預設的連接運算子。

+
如果兩個術語之間沒有布林運算符，則使用 OR 運算符。

+
OR 運算子連結兩個術語，如果其中一個術語存在於文件中，則尋找符合的文件。

+
例如，_storage OR netapp_ 搜尋包含 _storage_ 或 _netapp_ 的文檔。

+
與大多數術語相符的文件將獲得高分。

+
和

+
您可以使用 AND 運算子來尋找兩個搜尋字詞都存在於單一文件中的文件。例如，_storage AND netapp_ 搜尋同時包含 _storage_ 和 _netapp_ 的文檔。

+
您可以使用符號 *&&* 來代替單字 AND。

+
不是

+
當您使用 NOT 運算子時，所有包含 NOT 之後的術語的文件都將從搜尋結果中排除。例如，_storage NOT netapp_ 搜尋僅包含 _storage_ 而不包含 _netapp_ 的文件。

+
您可以使用符號 *!* 來代替單字 NOT。



搜尋不區分大小寫。



== 使用索引詞搜尋

與更多索引術語相符的搜尋會獲得更高的分數。

搜尋字串被空格分成單獨的搜尋詞。例如，搜尋字串「storage aurora netapp」被拆分為三個關鍵字：「storage」、「aurora」和「netapp」。使用所有三個術語進行搜尋。與大多數這些術語相符的文檔將獲得最高分數。您提供的資訊越多，搜尋結果就越好。例如，您可以按名稱和型號搜尋儲存空間。

使用者介面顯示跨類別的搜尋結果，每個類別顯示前三個結果。如果您沒有找到期望的對象，您可以在搜尋字串中包含更多術語以改善搜尋結果。

下表提供了可以新增到搜尋字串的索引術語清單。

|===
| 類別 | 索引術語 


| 儲存 | 「儲存」名稱供應商型號 


| 儲存池 | 「storagepool」名稱 儲存的名稱 儲存的 IP 位址 儲存的序號 儲存供應商 儲存型號 所有關聯內部磁碟區的名稱 所有關聯磁碟的名稱 


| 內部體積 | 「internalvolume」名稱 儲存的名稱 儲存的 IP 位址 儲存的序號 儲存供應商 儲存型號 儲存池的名稱 所有關聯共享的名稱 所有關聯應用程式的名稱 


| 體積 | 「磁碟區」名稱標籤所有內部磁碟區的名稱儲存池的名稱儲存的名稱儲存的 IP 位址儲存的序號儲存供應商儲存模型 


| 儲存節點 | 「storagenode」名稱 儲存的名稱 儲存的 IP 位址 儲存的序號 儲存供應商 儲存型號 


| 主持人 | “主機”名稱 IP 位址 所有相關應用程式的名稱 


| 資料儲存 | 「資料儲存區」名稱虛擬中心 IP 所有磁碟區的名稱所有內部磁碟區的名稱 


| 虛擬機 | 「虛擬機器」名稱 DNS 名稱 IP 位址 主機名稱 主機的 IP 位址 所有資料儲存區的名稱 所有關聯應用程式的名稱 


| 開關（常規和 NPV） | “交換器” IP 位址 wwn 名稱 序號 型號 域 ID 結構名稱 結構的 wwn 


| 應用 | 「應用程式」名稱 租戶 業務線 業務部門 項目 


| 磁帶 | “磁帶” IP位址名稱序號供應商 


| 港口 | “連接埠”WWN 名稱 


| 織物 | “織物” wwn 名稱 


| 儲存虛擬機器 (SVM) | 「storagevirtualmachine」名稱 UUID 
|===