---
sidebar: sidebar 
permalink: concept_asset_page_overview.html 
summary: 大多數物件類型都能顯示資產頁面。 
keywords: asset page, objects, landing page, Virtual machine, VM, Storage Virtual Machine, SVM, Volume, Internal volume, Host, Hypervisor, pool, Storage, Datastore, Application, node, Qtree, Disk, VMDK, Port, Switch, Fabric, refresh 
---
= 資產頁面總覽
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
資產頁面會摘要說明資產的目前狀態、並包含資產及其相關資產的其他資訊連結。



== 資產頁類型

Data Infrastructure Insights 提供下列資產的資產頁面：

* 虛擬機器
* 儲存虛擬機器（SVM）
* Volume
* 內部Volume
* 主機（包括Hypervisor）
* 儲存資源池
* 儲存設備
* 資料存放區
* 應用程式
* 儲存節點
* qtree
* 磁碟
* VMDK
* 連接埠
* 交換器
* 網路




== 變更顯示資料的時間範圍

依預設、資產頁面會顯示過去24小時的資料；不過、您可以選取其他固定時間範圍或自訂時間範圍來變更所顯示的資料區段、以檢視較少或更多的資料。

無論資產類型為何、您都可以使用位於每個資產頁面的選項來變更顯示資料的時間區段。若要變更時間範圍、請按一下頂端列中顯示的時間範圍、然後從下列時間段中選擇：

* 過去15分鐘
* 過去30分鐘
* 過去60分鐘
* 過去2小時
* 過去3小時（這是預設值）
* 過去6小時
* 過去12小時
* 過去24小時
* 過去 2 天
* 過去 3 天
* 過去 7 天
* 過去 30 天
* 自訂時間範圍


自訂時間範圍可讓您選擇最多連續31天。您也可以設定此範圍的開始時間和結束時間。預設的開始時間為所選第一天的上午 12 ： 00 ，所選最後一天的預設結束時間為下午 11 ： 59 。按一下「套用」將會將自訂時間範圍套用至資產頁面。

資產頁面摘要區段中的資訊、以及頁面上任何表格或自訂 Widget 中的資訊、會根據所選的時間範圍自動重新整理。目前的重新整理率會顯示在「摘要」區段的右上角、以及頁面上任何相關的表格或小工具上。



== 新增自訂小工具

您可以將自己的小工具新增至任何資產頁面。您新增的小工具會顯示在該類型所有物件的資產頁面上。例如、將自訂小工具新增至儲存資產頁面、會在所有儲存資產的資產頁面上顯示該小工具。
