---
sidebar: sidebar 
permalink: pre-requisites_for_k8s_operator.html 
keywords: telegraf, installation, install, agent, telegraf agent, kubernetes, eks, operator, k8s 
summary: Data Infrastructure Insights支援 Telegraf 作為其代理，用於收集 Kubernetes 上的整合資料。 
---
= 安裝或升級NetApp Kubernetes Monitoring Operator 前
:hardbreaks:
:allow-uri-read: 
:nofooter: 


[role="lead"]
在安裝或升級之前請閱讀此信息link:task_config_telegraf_agent_k8s.html["Kubernetes 監控操作員"]。

|===
| 成分 | 要求 


| Kubernetes 版本 | Kubernetes v1.20 以上版本。 


| Kubernetes 發行版 | AWS Elastic Kubernetes Service (EKS) Azure Kubernetes Service (AKS) Google Kubernetes Engine (GKE) Red Hat OpenShift Rancher Kubernetes Engine (RKE) VMware Tanzu 


| Linux 作業系統 | Data Infrastructure Insights不支援以 Arm64 架構運行的節點。網路監控：必須執行Linux核心4.18.0以上版本。不支援 Photon OS。 


| 標籤 | Data Infrastructure Insights支援監控執行 Linux 的 Kubernetes 節點，透過指定 Kubernetes 節點選擇器來尋找這些平台上的以下 Kubernetes 標籤：Kubernetes v1.20 及以上版本：Kubernetes.io/os = linux Rancher + cattle.io 作為業務流程/Kubernetes 平台：cattleux. 


| 命令 | curl 和 kubectl 指令必須可用；為了獲得最佳效果，請將這些指令加入 PATH。 


| 連接性 | kubectl cli 設定為與目標 K8s 叢集通信，並與您的Data Infrastructure Insights環境建立 Internet 連接。如果您在安裝過程中使用了代理，請按照link:task_config_telegraf_agent_k8s.html#configuring-proxy-support["配置代理支援"]操作員安裝部分。為了準確稽核和資料報告，請使用網路時間協定 (NTP) 或簡單網路時間協定 (SNTP) 同步代理電腦上的時間。 


| 其他 | 如果您在 OpenShift 4.6 或更高版本上執行，則必須遵循link:task_config_telegraf_agent_k8s.html#openshift-instructions["OpenShift 說明"]除了確保滿足這些先決條件之外。 


| API 令牌 | 如果您正在重新部署 Operator（即您正在更新或替換它），則無需建立新的 API 令牌；您可以重新使用先前的令牌。 
|===


== 開始前需要注意的重要事項

如果你正在跑步<<configuring-proxy-support,代理人>>，有一個<<using-a-custom-or-private-docker-repository,自訂儲存庫>>或正在使用<<openshift-instructions,OpenShift>>，請仔細閱讀以下章節。

另請參閱<<權限,權限>>。



=== 配置代理支援

您可以在租用戶的兩個地方使用代理程式來安裝NetApp Kubernetes 監控操作員。這些可能是相同或獨立的代理系統：

* 執行安裝程式碼片段（使用“curl”）期間需要代理，以將執行程式碼片段的系統連接到您的Data Infrastructure Insights環境
* 目標 Kubernetes 叢集與您的Data Infrastructure Insights環境通訊所需的代理


如果您對其中一個或兩個都使用代理，則要安裝NetApp Kubernetes 操作監視器，您必須先確保您的代理程式配置為允許與您的Data Infrastructure Insights環境進行良好的通訊。例如，從您希望安裝 Operator 的伺服器/虛擬機，您需要能夠存取Data Infrastructure Insights並能夠從Data Infrastructure Insights下載二進位檔案。

對於用於安裝NetApp Kubernetes Operating Monitor 的代理，在安裝 Operator 之前，請設定 _http_proxy/https_proxy_ 環境變數。對於某些代理環境，您可能還需要設定 _no_proxy 環境_變數。

若要設定變量，請在安裝NetApp Kubernetes Monitoring Operator*之前*在系統上執行下列步驟：

. 為目前使用者設定 _https_proxy_ 和/或 _http_proxy_ 環境變數：
+
.. 如果正在設定的代理程式沒有身份驗證（使用者名稱/密碼），請執行以下命令：
+
 export https_proxy=<proxy_server>:<proxy_port>
.. 如果正在設定的代理確實具有身份驗證（使用者名稱/密碼），請執行以下命令：
+
 export http_proxy=<proxy_username>:<proxy_password>@<proxy_server>:<proxy_port>




對於用於 Kubernetes 叢集與Data Infrastructure Insights環境通訊的代理，請在閱讀所有這些說明後安裝NetApp Kubernetes 監控操作員。

在部署NetApp Kubernetes Monitoring Operator 之前，請先設定 operator-config.yaml 中 AgentConfiguration 的代理程式部分。

[listing]
----
agent:
  ...
  proxy:
    server: <server for proxy>
    port: <port for proxy>
    username: <username for proxy>
    password: <password for proxy>

    # In the noproxy section, enter a comma-separated list of
    # IP addresses and/or resolvable hostnames that should bypass
    # the proxy
    noproxy: <comma separated list>

    isTelegrafProxyEnabled: true
    isFluentbitProxyEnabled: <true or false> # true if Events Log enabled
    isCollectorsProxyEnabled: <true or false> # true if Network Performance and Map enabled
    isAuProxyEnabled: <true or false> # true if AU enabled
  ...
...
----


=== 使用自訂或私有的 Docker 倉庫

預設情況下， NetApp Kubernetes 監控操作員將從Data Infrastructure Insights儲存庫中提取容器映像。如果您有 Kubernetes 叢集用作監控目標，且此叢集配置為僅從自訂或私人 Docker 儲存庫或容器註冊表中提取容器映像，則必須配置對NetApp Kubernetes 監控操作員所需容器的存取權。

從NetApp Monitoring Operator 安裝圖塊運行「Image Pull Snippet」。此命令將登入Data Infrastructure Insights儲存庫，為操作員提取所有影像依賴項，並登出Data Infrastructure Insights儲存庫。出現提示時，輸入提供的儲存庫臨時密碼。此命令下載操作員使用的所有影像，包括選用功能。請參閱下文以了解這些圖像的用途。

核心 Operator 功能和 Kubernetes 監控

* netapp-監控
* kube-rbac-代理
* kube 狀態指標
* 電訊報
* distroless-root 用戶


事件日誌

* 流利位
* kubernetes 事件匯出器


網路效能和地圖

* ci-net-觀察者


根據您的公司政策將操作員 docker 映像推送到您的私人/本地/企業 docker 儲存庫。確保儲存庫中這些圖像的圖像標籤和目錄路徑與Data Infrastructure Insights儲存庫中的一致。

編輯 operator-deployment.yaml 中的 monitoring-operator 部署，並修改所有映像引用以使用您的私人 Docker 儲存庫。

....
image: <docker repo of the enterprise/corp docker repo>/kube-rbac-proxy:<kube-rbac-proxy version>
image: <docker repo of the enterprise/corp docker repo>/netapp-monitoring:<version>
....
編輯 operator-config.yaml 中的 AgentConfiguration 以反映新的 docker repo 位置。為您的私人儲存庫建立一個新的 imagePullSecret，有關更多詳細信息，請參閱 _https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/_

[listing]
----
agent:
  ...
  # An optional docker registry where you want docker images to be pulled from as compared to CI's docker registry
  # Please see documentation for link:task_config_telegraf_agent_k8s.html#using-a-custom-or-private-docker-repository[using a custom or private docker repository].
  dockerRepo: your.docker.repo/long/path/to/test
  # Optional: A docker image pull secret that maybe needed for your private docker registry
  dockerImagePullSecret: docker-secret-name
----


=== OpenShift 說明

如果您在 OpenShift 4.6 或更高版本上執行，則必須編輯 _operator-config.yaml_ 中的 AgentConfiguration 以啟用 _runPrivileged_ 設定：

....
# Set runPrivileged to true SELinux is enabled on your kubernetes nodes
runPrivileged: true
....
Openshift 可能會實施額外的安全級別，從而阻止對某些 Kubernetes 元件的存取。



=== 權限

如果您正在監控的叢集包含沒有 ClusterRole 的自訂資源，link:https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles["要查看的聚合"] ，您將需要手動授予操作員存取這些資源的權限，以便使用事件日誌對其進行監控。

. 在安裝之前編輯 _operator-additional-permissions.yaml_，或在安裝之後編輯資源 _ClusterRole/<namespace>-additional-permissions_
. 使用動詞 ["get", "watch", "list"] 為所需的 apiGroups 和資源建立新規則。請參閱 \ https://kubernetes.io/docs/reference/access-authn-authz/rbac/
. 將更改應用到集群

