---
sidebar: sidebar 
permalink: reporting_publishing_annotations.html 
summary: 了解如何發布和取消發布註釋，以便在報告中使用。 
keywords: reporting, annotations, publish, unpublish, data warehouse, dwh 
---
= 發布和取消發布報告註釋
:allow-uri-read: 




== 發布和取消發布報告註釋

[role="lead"]
了解如何發布註釋以在報表和資料倉儲中使用，以及如何在不再需要註釋時正確地取消發布註釋。



== 發布報告註釋

在Data Infrastructure Insights中建立註釋後，您可以將其發布以在報表中使用。



=== 發布註釋的步驟

. 導覽至「可觀測性 > 豐富 > 註解」頁面，然後選擇「報表註解」標籤。
. 找到要發布的註釋。
. 選擇註釋，然後選擇「發佈到報表」。您也可以選擇將其套用至歷史數據，以便在執行歷史報表時使用該註解。
. 發布後，註釋即可在報告中使用。
. 註釋將在下次 ETL 運行後發布，以便在報告中使用。


[NOTE]
====
任何引用該註釋的報告都將使用已發布的值。如果在發布後修改了註釋，則可能需要重新發布才能使這些變更在報告中生效。

====


== 取消發布報告註釋

有時您可能需要刪除或取消發布註釋，以便它們不再用於報表。例如，某個註釋可能不再需要，或者它可能包含不應出現在報告中的過時資訊。



=== 取消發布註解的步驟

在取消發布註釋之前，請注意此操作將影響使用該註釋的任何現有報告。報告可能需要編輯或專業服務協助才能刪除註釋參考資訊。

. 在Data Infrastructure Insights使用者介面中，導覽至「報告註釋」標籤。
. 找到要取消發布的註釋。
. 對於每個已發布註釋的對象，取消選擇註釋並選擇「儲存」。
. 刪除所有仍引用該註釋的查詢或規則，以確保它不會被標記為「正在使用」。
. 下次 ETL 運行後，註解將被取消發布。
. ETL 完成後，如果租用戶端不再需要該註解，則可以將其從註解清單中刪除。


[IMPORTANT]
====
註釋將繼續顯示在資料倉儲中，直到被正確取消發佈為止。如果未先取消發布，直接從「註釋」頁面刪除註釋，則會留下過時的數據，這些數據可能會出現在現有報告中。請按照上述取消發布步驟操作，以確保徹底刪除。

====


== 對現有報告的影響

刪除或取消發布註釋可能需要修改引用這些註釋的現有報告。請考慮以下情況：

* 使用註釋作為篩選條件或維度的報告需要更新。
* 如果在未更新依賴報告的情況下刪除註釋，則這些報告可能會傳回錯誤或意外結果。
* 在複雜情況下，可能需要專業服務來協助進行報告修改。


建議在取消發布註釋之前，先檢查所有依賴該註釋的報告。
