---
sidebar: sidebar 
permalink: reporting_overview.html 
summary: 使用Data Infrastructure Insights對您的數據進行預先定義和自訂報告。 
keywords: reporting, cognos, data warehouse, dwh 
---
= Data Infrastructure Insights報告概述
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights報告是一種商業智慧工具，可讓您查看預先定義的報告或建立自訂報告。


NOTE: 報告功能可在Data Infrastructure Insights中使用link:concept_subscribing_to_cloud_insights.html["高級版"]。報告功能的可用性取決於最低佔用空間要求。link:https://www.netapp.com/forms/cloud-insights-contact-us/["聯絡您的NetApp銷售代表"]了解更多。

透過Data Infrastructure Insights報告，您可以執行以下任務：

* 運行預定義報告
* 建立自訂報告
* 自訂報告的格式和交付方式
* 安排報告自動運行
* 電子郵件報告
* 使用顏色表示資料閾值


Data Infrastructure Insights報告可以為退款、消費分析和預測等領域產生自訂報告，並可協助回答以下問題：

* 我有哪些庫存？
* 我的庫存在哪裡？
* 誰在使用我們的資產？
* 為業務部門分配的儲存空間的退款是多少？
* 我多久之後才需要獲得額外的儲存容量？
* 業務部門是否依照適當的儲存層進行排列？
* 儲存分配在一個月、一個季度或一年內如何變化？




== 存取Data Infrastructure Insights報告

您可以透過點擊選單中的「報告」連結來存取Data Infrastructure Insights報告。

您將進入報告介面。  Data Infrastructure Insights使用 IBM Cognos Analytics 作為其報表引擎。



== 什麼是 ETL？

在處理報表時，您會聽到術語「資料倉儲」和「ETL」。  ETL 代表「提取、轉換和載入」。  ETL 流程會擷取Data Infrastructure Insights中收集的數據，並將資料轉換為可用於報告的格式。  「資料倉儲」指可用於報表的收集資料。

ETL 過程包括以下單獨的過程：

* *擷取*：從Data Infrastructure Insights取得資料。
* *轉換*：將業務邏輯規則或功能應用於從Data Infrastructure Insights中提取的資料。
* *載入*：將轉換後的資料儲存到資料倉儲以供報表使用。

