---
sidebar: sidebar 
permalink: reporting_creating_custom_reports.html 
summary: 使用報告創作工具建立自訂（「臨時」）報告 
keywords: reporting, cognos, data warehouse, dwh, ad-hoc, custom 
---
= 建立自訂報告
:hardbreaks:
:allow-uri-read: 


[role="lead"]
您可以使用報告創作工具來建立自訂報告。建立報告後，您可以保存它們並定期運行它們。報告結果可以透過電子郵件自動發送給您自己和其他人。


NOTE: 報告功能可在Data Infrastructure Insights中使用link:concept_subscribing_to_cloud_insights.html["高級版"]。

本節中的範例展示了以下流程，可用於任何Data Infrastructure Insights報告資料模型：

* 確定需要透過報告回答的問題
* 確定支持結果所需的數據
* 選擇報告的數據元素


在設計自訂報告之前，您需要完成一些先決任務。如果您不完成這些，報告可能會不準確或不完整。

例如，如果您沒有完成設備識別過程，您的容量報告將不準確。或者，如果您沒有完成註釋設定（例如層級、業務部門和資料中心），您的自訂報告可能無法準確報告整個網域的數據，或者可能會對某些資料點顯示「N/A」。

在設計報告之前，請完成以下任務：

* 配置全部link:task_configure_data_collectors.html["數據收集者"]適當地。
* 在租戶的設備和資源上輸入註釋（例如層、資料中心和業務部門）。在產生報告之前穩定註釋是有益的，因為Data Infrastructure Insights報告會收集歷史資訊。




== 報表建立流程

建立自訂（也稱為「臨時」）報告的過程涉及幾項任務：

* 規劃報告的結果。
* 確定數據來支持您的結果。
* 選擇包含資料的資料模型（例如，Chargeback 資料模型、Inventory 資料模型等）。
* 選擇報告的數據元素。
* 可選擇格式化、排序和過濾報告結果。




=== 規劃自訂報告的結果

在開啟報告創作工具之前，您可能需要規劃您希望從報告中獲得的結果。使用報告創作工具，您可以輕鬆建立報告，並且可能不需要大量的規劃；但是，從報告請求者那裡了解報告要求是一個好主意。

* 確定您想要回答的確切問題。例如：
+
** 我還剩下多少容量？
** 每個業務部門的退款成本是多少？
** 各層的容量是多少，以確保業務單位在適當的儲存層上保持一致？
** 我如何預測電力和冷卻需求？  （透過向資源添加註釋來新增自訂元資料。）


* 確定支持答案所需的數據元素。
* 確定您想要在答案中看到的數據之間的關係。不要在問題中包含不合邏輯的關係，例如「我想查看與容量相關的連接埠」。
* 確定數據所需的任何計算。
* 確定需要哪些類型的過濾來限制結果。
* 確定是否需要使用當前資料或歷史資料。
* 確定是否需要設定報告的存取權限以將資料限制給特定受眾。
* 確定報告的分發方式。例如，是否應該按照設定的時間表透過電子郵件發送或包含在團隊內容資料夾區域？
* 確定誰來維護該報告。這可能會影響設計的複雜性。
* 建立報告的模型。




=== 設計報告的技巧

在設計報告時，一些技巧可能會有所幫助。

* 確定您是否需要使用當前資料或歷史資料。
+
大多數報告只需要報告Data Infrastructure Insights中可用的最新數據。

* Data Infrastructure Insights報告提供有關容量和性能的歷史信息，但不提供有關庫存的資訊。
* 每個人都可以看到所有數據；但是，您可能需要將數據限制給特定的受眾。
+
為了為不同的使用者細分訊息，您可以建立報告並設定存取權限。





== 報告資料模型

Data Infrastructure Insights包括幾個數據模型，您可以從中選擇預先定義的報告或建立自己的自訂報告。

每個資料模型包含一個簡單資料集市和一個進階資料集市：

* 簡單資料集市提供對最常用資料元素的快速訪問，並且僅包含資料倉儲資料的最新快照；它不包含歷史資料。
* 高級資料集市提供簡單資料集市的所有值和詳細信息，並包括對歷史資料值的存取。




=== 容量資料模型

使您能夠回答有關儲存容量、檔案系統使用率、內部磁碟區容量、連接埠容量、qtree 容量和虛擬機器 (VM) 容量的問題。容量資料模型是多個容量資料模型的容器。您可以使用此資料模型建立回答各種類型問題的報表：



==== 儲存和儲存池容量資料模型

使您能夠回答有關儲存容量資源規劃的問題，包括儲存和儲存池，並包括實體和虛擬儲存池資料。這個簡單的資料模型可以幫助您回答與場地容量以及按層和資料中心劃分的儲存池容量使用相關的問題。如果您對容量報告還不熟悉，那麼您應該從這個資料模型開始，因為它是一個更簡單、更有針對性的資料模型。您可以使用此資料模型回答類似以下的問題：

* 預計何時達到實體儲存容量閾值的 80%？
* 給定層的陣列的實體儲存容量是多少？
* 我的儲存容量按製造商、系列和資料中心劃分是多少？
* 陣列上所有層的儲存利用率趨勢如何？
* 我的利用率最高的 10 個儲存系統有哪些？
* 儲存池的儲存利用率趨勢如何？
* 已分配了多少容量？
* 可供分配的容量是多少？




==== 檔案系統利用率資料模型

此資料模型提供了檔案系統層級主機容量利用率的可見性。管理員可以確定每個檔案系統的分配和使用容量，確定檔案系統的類型，並按檔案系統類型識別趨勢統計資料。您可以使用此資料模型回答以下問題：

* 檔案系統的大小是多少？
* 資料保存在哪裡以及如何訪問，例如本地還是 SAN？
* 文件系統容量的歷史趨勢如何？那麼，基於此，我們可以預測未來的需求是什麼？




==== 內部磁碟區容量資料模型

使您能夠回答有關內部磁碟區已使用容量、已分配容量以及一段時間內的容量使用情況的問題：

* 哪些內部卷的利用率高於預定義閾值？
* 根據趨勢來看，哪些內部磁碟區面臨容量耗盡的危險？  8 我們的內部磁碟區的已使用容量與分配容量是多少？




==== 港口容量資料模型

使您能夠回答有關交換器連接埠連接、連接埠狀態和連接埠速度隨時間變化的問題。您可以回答類似以下的問題，以幫助您規劃購買新交換器：如何建立連接埠消耗預測，以預測資源（連接埠）可用性（根據資料中心、交換器供應商和連接埠速度）？

* 哪些連接埠可能會耗盡容量，提供資料速度、資料中心、供應商以及主機和儲存連接埠的數量？
* 交換器連接埠容量隨時間的變化趨勢如何？
* 連接埠速度是多少？
* 需要什麼類型的連接埠容量以及哪個組織即將耗盡某種連接埠類型或供應商？
* 購買該容量並使其可用的最佳時間是什麼時候？




==== Qtree 容量資料模型

讓您能夠隨時間推移了解 qtree 利用率趨勢（使用已使用容量與已分配容量等資料）。您可以按不同的維度查看資訊 - 例如，按業務實體、應用程式、層級和服務層級。您可以使用此資料模型回答以下問題：

* qtree 的使用容量與每個應用程式或業務實體設定的限制相比如何？
* 我們的已使用和可用容量的趨勢是什麼，以便我們可以進行容量規劃？
* 哪些商業實體使用的產能最多？
* 哪些應用程式消耗的容量最多？




==== 虛擬機器容量資料模型

使您能夠報告您的虛擬環境及其容量使用情況。此資料模型可讓您報告虛擬機器和資料儲存的容量使用隨時間的變化。此資料模型還提供精簡配置和虛擬機器退款資料。

* 如何根據為虛擬機器和資料儲存配置的容量確定容量分攤？
* 虛擬機器未使用哪些容量，哪些未使用的部分是空閒的、孤立的或其他的？
* 從消費趨勢來看我們需要購買什麼？
* 透過使用儲存精簡配置和重複資料刪除技術，我可以節省多少儲存效率？


VM 容量資料模型中的容量取自虛擬磁碟 (VMDK)。這意味著使用 VM 容量資料模型的 VM 的配置大小是其虛擬磁碟的大小。這與Data Infrastructure Insights中的虛擬機器視圖中的預先配置容量不同，後者顯示的是虛擬機器本身的預先配置大小。



==== 卷容量資料模型

使您能夠分析租戶卷的各個方面，並按供應商、型號、層級、服務等級和資料中心組織資料。

您可以查看與孤立磁碟區、未使用磁碟區和保護磁碟區（用於複製）相關的容量。您也可以看到不同的磁碟區技術（iSCSI 或 FC），並將虛擬磁碟區與非虛擬磁碟區進行比較，以解決陣列虛擬化問題。

您可以使用此資料模型回答類似以下的問題：

* 哪些卷的利用率高於預先定義的閾值？
* 我的資料中心的孤立磁碟區容量趨勢如何？
* 我的資料中心容量有多少是虛擬化的或精簡配置的？
* 我的資料中心必須保留多少容量用於複製？




=== 退款資料模型

使您能夠回答有關儲存資源（磁碟區、內部磁碟區和 qtree）的已使用容量和已指派容量的問題。此資料模型提供主機、應用程式和業務實體的儲存容量退款和責任信息，包括當前資料和歷史資料。報告資料可以按服務等級和儲存層進行分類。

您可以使用此資料模型透過尋找業務實體使用的容量來產生退款報告。此資料模型可讓您建立多種協定（包括 NAS、SAN、FC 和 iSCSI）的統一報表。

* 對於沒有內部卷的存儲，退款報告顯示按卷進行的退款。
* 對於具有內部磁碟區的儲存：
+
** 如果將業務實體指派給卷，則分攤報表會依卷顯示分攤。
** 如果業務實體未分配給磁碟區但分配給 qtree，則分攤報表將顯示按 qtree 進行的分攤。
** 如果業務實體未指派給磁碟區且未指派給 qtree，則分攤報表將顯示內部磁碟區。
** 是否按卷、qtree 或內部卷顯示費用分攤是由每個內部卷決定的，因此同一存儲池中的不同內部卷可以顯示不同級別的費用分攤。




容量事實會在預設時間間隔後清除。有關詳細信息，請參閱資料倉儲流程。

使用 Chargeback 資料模型的報表可能與使用 Storage Capacity 資料模型的報表顯示不同的值。

* 對於非NetApp儲存系統的儲存陣列，來自兩個資料模型的資料是相同的。
* 對於NetApp和 Celerra 儲存系統，Chargeback 資料模型使用單層（磁碟區、內部磁碟區或 qtree）來作為收費依據，而儲存容量資料模型則使用多層（磁碟區和內部磁碟區）作為收費依據。




=== 庫存資料模型

使您能夠回答有關庫存資源的問題，包括主機、儲存系統、交換器、磁碟、磁帶、qtree、配額、虛擬機器和伺服器以及通用設備。庫存資料模型包括幾個子市場，使您能夠查看有關複製、FC 路徑、iSCSI 路徑、NFS 路徑和違規的資訊。庫存資料模型不包括歷史資料。您可以利用這些數據回答的問題

* 我擁有哪些資產？它們在哪裡？
* 誰在使用這些資產？
* 我有哪些類型的設備以及這些設備的組件是什麼？
* 每個作業系統有多少個主機以及這些主機上有多少個連接埠？
* 每個資料中心每個供應商有哪些儲存陣列？
* 每個資料中心每個供應商有多少台交換器？
* 有多少連接埠未獲得許可？
* 我們使用的是哪些供應商的磁帶，每個磁帶上有多少個連接埠？在我們開始編寫報告之前，是否已經識別了所有通用設備？
* 主機和儲存磁碟區或磁帶之間的路徑是什麼？
* 通用設備和儲存磁碟區或磁帶之間的路徑是什麼？
* 每個資料中心每種類型的違規行為有多少次？
* 對於每個複製卷，來源捲和目標卷是什麼？
* 光纖通道主機 HBA 和交換器之間是否存在韌體不相容或連接埠速度不匹配的情況？




=== 性能數據模型

使您能夠回答有關磁碟區、應用程式磁碟區、內部磁碟區、交換器、應用程式、虛擬機器、VMDK、ESX 與虛擬機器、主機和應用程式節點的效能問題。其中許多報告是「每小時」數據、「每日」數據或兩者兼有。使用此資料模型，您可以建立回答多種類型的績效管理問題的報表：

* 在特定時間內哪些磁碟區或內部磁碟區尚未被使用或存取？
* 我們能否找出應用程式（未使用）儲存的任何潛在錯誤配置？
* 應用程式的整體存取行為模式是什麼？
* 分層卷是否適合給定的應用程式？
* 我們能否為目前正在運行的應用程式使用更便宜的儲存而不會影響應用程式效能？
* 哪些應用程式對目前配置的儲存產生更多的存取？


使用交換器效能表時，您可以獲得以下資訊：

* 我的主機通過連接埠的流量是否均衡？
* 哪些交換器或連接埠出現大量錯誤？
* 根據連接埠效能，最常用的交換器有哪些？
* 根據連接埠效能，哪些交換器未充分利用？
* 基於連接埠效能的主機趨勢吞吐量是多少？
* 指定主機、儲存系統、磁帶或交換器過去 X 天的效能使用率為何？
* 哪些設備在特定交換器上產生流量（例如，哪些設備負責使用高使用率的交換器）？
* 我們的環境中特定業務部門的吞吐量為何？


使用磁碟效能表時，您可以獲得以下資訊：

* 根據磁碟效能數據，指定儲存池的吞吐量為何？
* 使用率最高的儲存池是什麼？
* 特定儲存的平均磁碟利用率是多少？
* 根據磁碟效能數據，儲存系統或儲存池的使用趨勢如何？
* 特定儲存池的磁碟使用趨勢如何？


使用 VM 和 VMDK 效能表時，您可以獲得以下資訊：

* 我的虛擬環境是否表現最佳？
* 哪些 VMDK 報告的工作負載最高？
* 如何使用映射到不同資料儲存的 VMD 報告的效能來做出有關重新分層的決策。


效能資料模型包含可協助您確定層的適當性、應用程式的儲存錯誤配置以及磁碟區和內部磁碟區的最後存取時間的資訊。此資料模型提供回應時間、IOP、吞吐量、待處理寫入數和存取狀態等資料。



=== 儲存效率資料模型

使您能夠追蹤儲存效率得分和一段時間內的潛力。此資料模型不僅儲存了已配置容量的測量值，還儲存了已使用或消耗的容量（實體測量值）。例如，當啟用精簡配置時，Data Infrastructure Insights指示從設備中獲取了多少容量。您也可以使用此模型來確定啟用重複資料刪除時的效率。您可以使用儲存效率資料集市來回答各種問題：

* 透過實作精簡配置和重複資料刪除技術，我們的儲存效率節省了多少？
* 跨資料中心的儲存節省是多少？
* 根據歷史容量趨勢，我們何時需要購買額外的儲存空間？
* 如果我們啟用精簡配置和重複資料刪除等技術，容量會有多大？
* 關於儲存容量，我現在有風險嗎？




=== 資料模型事實表與維度表

每個資料模型都包括事實表和維度表。

* 事實表：包含測量的數據，例如數量、原始容量和可用容量。包含維度表的外鍵。
* 維度表：包含有關事實的描述信息，例如資料中心和業務部門。維度是一種將資料分類的結構，通常由層次結構組成。維度屬性有助於描述維度值。


使用不同或多個維度屬性（在報表中顯示為列），您可以建立存取資料模型中所述的每個維度的資料的報表。



=== 資料模型元素中使用的顏色

資料模型元素上的顏色有不同的意義。

* 黃色資產：代表測量值。
* 非黃色資產：代表屬性。這些值不聚合。




=== 在一個報告中使用多個資料模型

通常，每個報告使用一個資料模型。但是，您可以編寫一份包含來自多個資料模型的資料的報告。

若要撰寫包含來自多個資料模型的資料的報告，請選擇其中一個資料模型作為基礎，然後編寫 SQL 查詢來存取來自其他資料集市的資料。您可以使用 SQL Join 功能將來自不同查詢的資料組合成一個查詢，以便用於編寫報表。

例如，假設您想要每個儲存陣列的目前容量，並且想要擷取陣列上的自訂註解。您可以使用儲存容量資料模型建立報表。您可以使用目前容量和維度表中的元素，並新增單獨的 SQL 查詢來存取庫存資料模型中的註釋資訊。最後，您可以使用儲存名稱和連接條件將庫存儲存資料連結到儲存維度表，從而合併資料。
