---
sidebar: sidebar 
permalink: security_information_and_region.html 
summary: Data Infrastructure Insights 在整個版本生命週期中遵循安全性最佳實務做法。 
keywords: security, risk, protection 
---
= 資訊與地區
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetApp非常重視客戶資訊的安全性。以下是 Data Infrastructure Insights 儲存您資訊的方式和位置。



== Data Infrastructure Insights 儲存哪些資訊？

Data Infrastructure Insights 儲存下列資訊：

* 效能資料
+
效能資料是時間序列資料、提供有關受監控裝置/來源效能的資訊。例如、這包括儲存系統所交付的IOS數量、Fibre Channel連接埠的處理量、Web伺服器所傳送的頁數、資料庫的回應時間等等。

* 庫存資料
+
庫存資料包含中繼資料、說明受監控的裝置/來源及其設定方式。例如、其中包括安裝的硬體和軟體版本、儲存系統中的磁碟和LUN、CPU核心、虛擬機器的RAM和磁碟、資料庫的表格空間、SAN交換器上的連接埠數目和類型、目錄/檔案名稱（如果已啟用儲存工作負載安全功能）等

* 組態資料
+
此摘要說明客戶提供的組態資料、用於管理客戶的庫存和作業、例如受監控裝置的主機名稱或IP位址、輪詢時間間隔、逾時值等

* 機密
+
機密包含 Data Infrastructure Insights Acquisition Unit 用來存取客戶裝置和服務的認證資料。這些認證會使用強式非對稱式加密來加密、私密金鑰只會儲存在擷取單元上、絕不會離開客戶環境。即使是特權資料基礎架構 Insights SRE 也無法以純文字存取客戶機密資料、因為這項設計。

* 功能資料
+
這是NetApp提供雲端資料服務所產生的資料、可讓NetApp在雲端資料服務的開發、部署、營運、維護及安全方面、掌握最新資訊。功能資料不包含客戶資訊或個人資訊。

* 使用者存取資料
+
允許NetApp控制台與區域Data Infrastructure Insights站點通訊的身份驗證和存取訊息，包括與使用者授權相關的資料。

* 儲存工作負載安全性使用者目錄資料
+
如果啟用工作負載安全功能、且客戶選擇啟用使用者目錄收集器、系統會儲存使用者顯示名稱、公司電子郵件地址、以及從Active Directory收集的其他資訊。




NOTE: 使用者目錄資料是指由工作負載安全性使用者目錄資料收集器所收集的使用者目錄資訊、而非資料基礎架構 Insights / 工作負載安全性本身的使用者相關資料。

*不會從基礎架構和服務資源收集明確的個人資料*。收集的資訊僅包含效能指標、組態資訊和基礎架構中繼資料、與許多廠商的電話公司（包括NetApp自動支援和ActiveIQ）非常相似。不過、視客戶的命名慣例而定、共享區、磁碟區、VM、qtree、 應用程式等可能包含個人識別資訊。

如果啟用「工作負載安全性」、系統會額外查看SMB或其他共用區上的檔案和目錄名稱、這些檔案和目錄名稱可能包含個人識別資訊。當客戶啟用工作負載安全性使用者目錄收集器（主要透過 Active Directory 將 Windows SID 對應至使用者名稱）時、「 Data Infrastructure Insights 」會收集並儲存顯示名稱、公司電子郵件地址和任何其他選取的屬性。

此外、也會維護 Data Infrastructure Insights 的存取記錄、其中包含使用者用來登入服務的 IP 和電子郵件地址。



== 我的資訊儲存在何處？

Data Infrastructure Insights 會根據建立環境的區域來儲存資訊。

下列資訊儲存在主機區域中：

* 遙測與資產/物件資訊、包括計數器和效能指標
* 擷取單位資訊
* 功能資料
* 資料基礎架構洞見內的使用者活動稽核資訊
* 工作負載安全性Active Directory資訊
* 工作負載安全稽核資訊


無論資料基礎架構 Insights 環境所在的地區為何、下列資訊都位於美國境內：

* 環境網站（有時稱為「租戶」）資訊、例如網站/帳戶擁有者。
* 允許NetApp控制台與區域Data Infrastructure Insights通訊的訊息，包括與使用者授權有關的任何資訊。
* 與 Data Infrastructure Insights 使用者與租戶之間關係相關的資訊。




=== 主機區域

主機區域包括：

* 美國：美國-東1
* EMEA：EU-Central 1
* 亞太地區：AP-東南亞-2




== 更多資訊

如需更多關於NetApp隱私權與安全性的資訊、請參閱下列連結：

* link:https://www.netapp.com/us/company/trust-center/index.aspx["信任中心"]
* link:https://www.netapp.com/us/company/trust-center/privacy/data-location-cross-border-transfers.aspx["跨境資料傳輸"]
* link:https://www.netapp.com/us/company/trust-center/privacy/bcr-binding-corporate-rules.aspx["具約束力的企業規則"]
* link:https://www.netapp.com/us/company/trust-center/transparency/third-party-data-requests.aspx["回應第三方資料要求"]
* link:https://www.netapp.com/us/company/trust-center/privacy/privacy-principles-security-safeguards.aspx["NetApp隱私權原則"]

