---
sidebar: sidebar 
permalink: security_information_and_region.html 
summary: Data Infrastructure Insights在整個發布生命週期中遵循安全最佳實踐。 
keywords: security, risk, protection 
---
= 資訊和區域
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetApp非常重視客戶資訊的安全。以下是Data Infrastructure Insights儲存您的資訊的方式和位置。



== Data Infrastructure Insights儲存哪些資訊？

Data Infrastructure Insights儲存以下資訊：

* 效能數據
+
性能數據是提供有關受監控設備/源性能的信息的時間序列數據。例如，這包括儲存系統傳送的 IO 數量、光纖通道連接埠的吞吐量、Web 伺服器傳送的頁面數量、資料庫的回應時間等等。

* 庫存數據
+
庫存資料由描述受監控設備/來源及其配置方式的元資料組成。例如，這包括安裝的硬體和軟體版本、儲存系統中的磁碟和 LUN、虛擬機器的 CPU 核心、RAM 和磁碟、資料庫的表空間、SAN 交換器上的連接埠數量和類型、目錄/檔案名稱（如果啟用了儲存工作負載安全性）等。

* 配置數據
+
這總結了用於管理客戶庫存和操作的客戶提供的配置數據，例如受監控設備的主機名稱或 IP 位址、輪詢間隔、逾時值等。

* 秘密
+
機密包括Data Infrastructure Insights獲取單元用於存取客戶設備和服務的憑證。這些憑證使用強非對稱加密進行加密，並且私鑰僅儲存在採集單元上，永遠不會離開客戶環境。由於這種設計，即使是特權Data Infrastructure InsightsSRE 也無法以純文字形式存取客戶機密。

* 功能數據
+
這是NetApp提供雲端資料服務時產生的數據，用於為NetApp提供雲端資料服務的開發、部署、營運、維護和保護資訊。功能數據不包含客戶資訊或個人資訊。

* 使用者存取數據
+
允許NetApp Console與區域Data Infrastructure Insights站點通訊的身份驗證和存取訊息，包括與使用者授權相關的資料。

* 儲存工作負載安全用戶目錄數據
+
如果啟用了工作負載安全功能且客戶選擇啟用使用者目錄收集器，系統將儲存從 Active Directory 收集的使用者顯示名稱、公司電子郵件地址和其他資訊。




NOTE: 使用者目錄資料是指工作負載安全使用者目錄資料收集器收集的使用者目錄信息，而不是Data Infrastructure Insights/工作負載安全使用者本身的資料。

*沒有從基礎設施和服務資源收集明確的個人資料*。收集的資訊僅包括效能指標、配置資訊和基礎設施元數據，與許多供應商電話主頁非常相似，包括NetApp自動支援和 ActiveIQ。但是，根據客戶的命名約定，共用、磁碟區、虛擬機器、配額樹、應用程式等的資料可能包含個人識別資訊。

如果啟用了工作負載安全，系統也會查看 SMB 或其他共用上的檔案和目錄名稱，其中可能包含個人識別資訊。當客戶啟用工作負載安全性使用者目錄收集器（其本質上是透過 Active Directory 將 Windows SID 對應到使用者名稱）時，Data Infrastructure Insights將收集和儲存顯示名稱、公司電子郵件地址和任何選定的附加屬性。

此外，還會維護Data Infrastructure Insights的存取日誌，其中包含用於登入服務的使用者 IP 和電子郵件地址。



== 我的資訊儲存在哪裡？

Data Infrastructure Insights根據您創建環境的區域儲存資訊。

主機區域中儲存以下資訊：

* 遙測和資產/物件訊息，包括計數器和性能指標
* 採集單元資訊
* 功能數據
* 審計Data Infrastructure Insights內部使用者活動的訊息
* 工作負載安全性 Active Directory 訊息
* 工作負載安全審計信息


無論您的Data Infrastructure Insights環境託管在哪個區域，以下資訊都位於美國：

* 環境站點（有時稱為“租戶”）訊息，例如站點/帳戶所有者。
* 允許NetApp Console與區域Data Infrastructure Insights通訊的信息，包括與使用者授權有關的任何資訊。
* 與Data Infrastructure Insights用戶和租戶之間的關係相關的資訊。




=== 主辦地區

主辦地區包括：

* 美國：us-east-1
* 歐洲、中東和非洲地區：eu-central-1
* 亞太地區：ap-southeast-2




== 更多資訊

您可以透過以下連結了解更多有關 NetApp 隱私和安全性的資訊：

* link:https://www.netapp.com/us/company/trust-center/index.aspx["信任中心"]
* link:https://www.netapp.com/us/company/trust-center/privacy/data-location-cross-border-transfers.aspx["跨境資料傳輸"]
* link:https://www.netapp.com/us/company/trust-center/privacy/bcr-binding-corporate-rules.aspx["具有約束力的公司規則"]
* link:https://www.netapp.com/us/company/trust-center/transparency/third-party-data-requests.aspx["回應第三方資料請求"]
* link:https://www.netapp.com/us/company/trust-center/privacy/privacy-principles-security-safeguards.aspx["NetApp隱私原則"]

