---
sidebar: sidebar 
permalink: task_dc_emc_unisphere_rest.html 
keywords: data collector, Unisphere, EMC 
summary: 配置 Dell EMC Unisphere REST 資料收集器。 
---
= 配置 Dell EMC Unisphere REST 資料收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
此資料收集器從 Dell EMC Unisphere 取得 PowerMax / Vmax 3 管理系統的庫存和效能資料。

請注意，Dell/EMC 直到 Unisphere 10.0 才引入每個卷的統計數據 - 此數據收集器支援 9.2.0+，但無法收集卷統計數據，因為它們不存在。

一個 Unisphere for Vmax/PowerMax 執行個體可能正在管理一個或多個 Symmetrix Vmax 3 或更高版本的儲存陣列 - 此收集器將預設嘗試發現該 Unisphere 執行個體的所有「本機」儲存陣列。如果 Unisphere 實例看到「遠端」陣列（即透過 SRDF 複製連接的陣列），它們將被忽略，並且要發現這些陣列，您應該在Data Infrastructure Insights中建立額外的 Unisphere 收集器，指向該站點中將它們視為本地的任何 Unisphere 實例。

對於配置，資料收集器需要 Unisphere 伺服器的 IP 位址/FQDN、與連接埠 8443 的 TCP 連線以及使用者名稱和密碼。



== 要求

* Unisphere 伺服器的 IP 位址/完全限定域名
* 使用者名稱和密碼
* 端口 8443。




== 配置

[cols="2*"]
|===
| 場地 | 描述 


| Unisphere 伺服器的 IP 位址 | Unisphere 伺服器的 IP 位址或完全限定域名 


| Unisphere 連接埠 | 預設值為 8443 


| 使用者名稱 | Unisphere 伺服器的使用者名稱 


| 密碼 | Unisphere 伺服器使用的密碼 
|===


== 進階配置

[cols="2*"]
|===
| 場地 | 描述 


| 庫存輪詢間隔（分鐘） | 預設值為 40 分鐘。 


| 效能輪詢間隔（秒） | 效能輪詢之間的間隔。 


| 選擇“排除”或“包含”來指定列表 | 指定是否包含或排除虛擬機 


| 庫存過濾器設備列表 | 要過濾的虛擬機器清單（以逗號分隔，如果值中使用逗號，則以分號分隔）以進行過濾 


| Unisphere 效能輪詢間隔（秒） | 預設值為 300 秒 
|===


== 故障排除

如果您在使用此資料收集器時遇到問題，請嘗試以下操作：



=== 存貨

[cols="2*"]
|===
| 問題： | 試試一下： 


| 錯誤：使用者身份驗證失敗。 | 確保您對此裝置的憑證正確無誤。 


| 庫存最新狀態：檢索到意外資料 - 陣列報告卷數為 0 | 通常表示授權（而非身分驗證）問題。確保您的憑證正確，並且使用者名稱有權列出所有磁碟區並查看其屬性。 
|===
更多資訊可從link:concept_requesting_support.html["支援"]頁面或在link:reference_data_collector_support_matrix.html["數據收集器支援矩陣"]。
