---
sidebar: sidebar 
permalink: task_dc_hds_ops_center.html 
keywords: data collector, Hitachi Ops Center 
summary: 配置 HDS Ops Center 資料收集器。 
---
= Hitachi Ops Center 資料收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
此資料收集器使用 Hitachi Ops Center 的整合應用程式套件來存取多個儲存設備的庫存和效能資料。對於庫存和容量發現，您的 Ops Center 安裝必須同時包含「通用服務」和「管理員」元件。為了進行效能收集，您還必須部署「分析器」。



== 術語

Data Infrastructure Insights從該數據收集器獲取以下庫存資訊。對於Data Infrastructure Insights取得的每種資產類型，都會顯示用於該資產的最常用術語。當查看或排除此資料收集器的故障時，請記住以下術語：

[cols="2*"]
|===
| 供應商/型號術語 | Data Infrastructure Insights術語 


| 儲存系統 | 儲存 


| 體積 | 體積 


| 奇偶校驗組 | 儲存池（RAID）、磁碟組 


| 磁碟 | 磁碟 


| 儲存池 | 儲存池（Thin、SNAP） 


| 外部奇偶校驗組 | 儲存池（後端）、磁碟組 


| 港口 | 儲存節點 → 控制節點 → 連接埠 


| 主機群組 | 體積映射和遮罩 


| 交易量對 | 儲存同步 
|===
注意：這些只是常見的術語映射，可能並不代表此資料收集器的所有情況。



== 庫存需求

為了收集庫存數據，您必須具備以下條件：

* 託管「公用服務」元件的 Ops Center 伺服器的 IP 位址或主機名
* 所有託管 Ops Center 元件的伺服器上都存在 Root/sysadmin 使用者帳戶和密碼。直到 Ops Center 10.8+ 版本，HDS 才實作 REST API 支援供 LDAP/SSO 使用者使用




== 性能要求

為了收集性能數據，必須滿足以下要求：

必須安裝 HDS Ops Center「分析器」模組 儲存陣列必須為 Ops Center「分析器」模組提供數據



== 配置

[cols="2*"]
|===
| 場地 | 描述 


| Hitachi Ops Center IP 位址 | 託管「通用服務」元件的 Ops Center 伺服器的 IP 位址或完全限定域名 


| 使用者名稱 | Ops Center 伺服器的使用者名稱。 


| 密碼 | 用於 Ops Center 伺服器的密碼。 
|===


== 進階配置

|===


| 場地 | 描述 


| 連接類型 | HTTPS（連接埠 443）是預設連接埠 


| 覆蓋 TCP 連接埠 | 指定要使用的連接埠（如果不是預設連接埠） 


| 庫存輪詢間隔（分鐘） | 庫存調查之間的間隔。預設值為 40。 


| 選擇“排除”或“包含”來指定列表 | 指定收集資料時是否包含或排除以下數組清單。 


| 過濾設備列表 | 要包含或排除的設備序號的逗號分隔列表 


| 效能輪詢間隔（秒） | 效能輪詢之間的間隔。預設值為 300。 
|===
更多資訊可從link:concept_requesting_support.html["支援"]頁面或在link:reference_data_collector_support_matrix.html["數據收集器支援矩陣"]。
