---
sidebar: sidebar 
permalink: task_dc_na_amazon_fsx.html 
keywords: 'data collector, stout, fsx, fsx-netapp, Amazon, AWS, cluster, volume, share, LUN"' 
summary: Amazon FSx for NetApp ONTAP 
---
= Amazon FSx for NetApp ONTAP資料收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
此資料收集器從Amazon FSx for NetApp ONTAP取得庫存和效能資料。此資料收集器將逐步在整個Data Infrastructure Insights服務區域內提供。如果您在Data Infrastructure Insights環境中沒有看到此收集器的圖標，請聯絡您的銷售人員。


NOTE: 此Data Infrastructure Insights收集器需要具有_Filesystem-Scoped_角色的ONTAP使用者。請查看 AWSlink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/roles-and-users.html["角色和規則"]可用選項的文件。目前 AWS 僅支援一種具有檔案系統範圍的使用者角色，即 _fsxadmin_。這是適合Data Infrastructure Insights收集器使用的角色。用戶還應該分配以下三個應用程式：http、ontapi、ssh。



== 術語

Data Infrastructure Insights從 FSx- NetApp資料收集器取得庫存和效能資料。對於所取得的每種資產類型，都會顯示該資產最常用的術語。當查看或排除此資料收集器的故障時，請記住以下術語：

[cols="2*"]
|===
| 供應商/型號術語 | Data Infrastructure Insights術語 


| 簇 | 儲存 


| 邏輯單元號 | 體積 


| 體積 | 內部體積 
|===


== FSx- NetApp術語

以下術語適用於您可能在 FSx- NetApp儲存資產登入頁面上找到的物件或參考。其中許多術語也適用於其他資料收集器。



=== 儲存

* 模型 – 此叢集內唯一、離散的模型名稱的逗號分隔清單。
* 供應商 – AWS
* 序號 – 陣列序號。
* IP – 通常是資料來源中配置的 IP 或主機名稱。
* 原始容量 – 分配給 FSx 檔案系統的所有 SSD 儲存的以 2 為底的總和。
* 延遲－表示主機在讀取和寫入過程中所面臨的工作負載的情況。理想情況下，Data Infrastructure Insights會直接取得該數值，但事實往往並非如此。取代提供此功能的陣列，Data Infrastructure Insights通常會執行根據各個內部卷的統計資料得出的 IOP 加權計算。
* 吞吐量－從內部磁碟區聚合而成。管理－這可能包含裝置管理介面的超連結。由Data Infrastructure Insights資料來源以程式設計方式創建，作為庫存報告的一部分。




=== 儲存池

* 儲存－該池位於哪個儲存陣列上。強制的。
* 類型－來自可能性枚舉清單的描述性值。最常見的是「聚合」或「RAID 群組」」。
* 容量－這裡的值是邏輯已使用容量、可用容量和邏輯總容量，以及這些容量中使用的百分比。
* IOPS – 此儲存池上指派的所有磁碟區的 IOP 總和。
* 吞吐量－此儲存池上指派的所有磁碟區的總吞吐量。




== 要求

以下是配置和使用此資料收集器的要求：

* 您必須具有「fsxadmin」角色的帳戶存取權限，並為其分配三個應用程式 - ssh、ontapi、http
* 帳戶詳細資訊包括使用者名稱和密碼。
* 連接埠要求：443




== 配置

[cols="2*"]
|===
| 場地 | 描述 


| NetApp管理 IP | NetApp叢集的 IP 位址或完全限定域名 


| 使用者名稱 | NetApp叢集的使用者名稱 


| 密碼 | NetApp叢集密碼 
|===


== 進階指標

此資料收集器從 FSx for NetApp ONTAP儲存收集以下進階指標：

* 政策
* nfsv3
* nfsv3：節點
* nfsv4
* nfsv4_1
* nfsv4_1:節點
* nfsv4：節點
* 策略組
* 配額樹
* 體積
* 工作負載量


請注意，FSx CLI 和 API 指令會擷取Data Infrastructure Insights ZAPI 未收集的一些容量值，因此Data Infrastructure Insights中的某些容量值（例如儲存池的容量值）可能與 FSx 本身上的容量值不同。



== 故障排除

如果您在使用此資料收集器時遇到問題，請嘗試以下操作：



=== 存貨

[cols="2*"]
|===
| 問題： | 試試一下： 


| 收到 401 HTTP 回應或 13003 ZAPI 錯誤代碼，並且 ZAPI 返回“權限不足”或“未授權執行此命令” | 檢查使用者名稱和密碼以及使用者權限/許可。 


| ZAPI 傳回“群集角色不是 cluster_mgmt LIF” | AU 需要與叢集管理 IP 對話。檢查 IP 並在必要時更改為其他 IP 


| 重試後 ZAPI 指令失敗 | AU 與集群有通訊問題。檢查網路、連接埠號碼和 IP 位址。使用者還應該嘗試從 AU 機器的命令列運行命令。 


| AU 無法透過 HTTP 連線到 ZAPI | 檢查 ZAPI 連接埠是否接受純文字。如果 AU 嘗試向 SSL 套接字發送純文本，則通訊失敗。 


| 通訊失敗並出現 SSLException | AU 正在嘗試將 SSL 傳送到檔案總管上的純文字連接埠。檢查 ZAPI 連接埠是否接受 SSL，或使用其他連接埠。 


| 其他連接錯誤： ZAPI 回應的錯誤代碼為 13001，“資料庫未開啟” ZAPI 錯誤代碼為 60，回應包含“API 未按時完成” ZAPI 回應包含“initialize_session() 傳回 NULL 環境” ZAPI 錯誤代碼為 14007，回應包含“節點不健康” | 檢查網路、連接埠號碼和 IP 位址。使用者還應該嘗試從 AU 機器的命令列運行命令。 
|===
更多資訊可從link:concept_requesting_support.html["支援"]頁面或在link:reference_data_collector_support_matrix.html["數據收集器支援矩陣"]。
