---
sidebar: sidebar 
permalink: task_device_resolution_rules.html 
keywords: Automatic, AR, AHR, Host, automatic device resolution 
summary: 設備解析度可協助您準確追蹤環境中的效能和庫存。 
---
= 設備解析規則
:hardbreaks:
:allow-uri-read: 


[role="lead"]
您可以建立設備解析規則來識別Data Infrastructure Insights目前無法自動識別的主機、儲存和磁帶。您建立的規則可以識別目前環境中的設備，也可以識別新增到環境中的類似設備。



== 建立設備解析規則

在建立規則時，首先要確定規則所針對的資訊來源、用於提取資訊的方法以及是否將 DNS 查找應用於規則的結果。

[cols="2*"]
|===


| 用於識別設備的來源 | * 主機的 SRM 別名 * 包含嵌入式主機或磁帶名稱的儲存別名 * 包含嵌入式主機或磁帶名稱的交換器別名 * 包含嵌入式主機名稱的區域名稱 


| 用於從來源中提取設備名稱的方法 | * 以原樣（從 SRM 中提取名稱）* 分隔符號* 正規表示式 


| DNS查找 | 指定是否使用 DNS 來驗證主機名 
|===
您可以在「自動解決規則」標籤中建立規則。以下步驟描述了規則建立過程。

.程式
. 按一下“管理”>“裝置解析度”
. 在「自動解析規則」標籤中，按一下「+ 主機規則」或「+ 磁帶規則」。
+
顯示「*解決規則*」畫面。

+

NOTE: 按一下「檢視符合條件」連結以取得建立正規表示式的協助和範例。

. 在*類型*清單中選擇您想要識別的裝置。
+
您可以選擇_Host_或_Tape_。

. 在「*來源*」清單中，選擇要用於識別主機的來源。
+
根據您選擇的來源，Data Infrastructure Insights將顯示以下回應：

+
.. *Zones* 列出了Data Infrastructure Insights需要識別的區域和 WWN。
.. *SRM* 列出了需要由Data Infrastructure Insights識別的未識別別名
.. *儲存別名*列出了需要由Data Infrastructure Insights識別的儲存別名和 WWN
.. *交換器別名*列出了需要由Data Infrastructure Insights識別的交換器別名


. 在*方法*清單中選擇您想要用來識別主機的方法。
+
|===


| 來源 | 方法 


| 開關磁阻電機 | 原樣，分隔符，正規表示式 


| 儲存別名 | 分隔符號、正規表示式 


| 切換別名 | 分隔符號、正規表示式 


| 區域 | 分隔符號、正規表示式 
|===
+
** 使用分隔符號的規則需要分隔符號和主機名稱的最小長度。主機名稱的最小長度是Data Infrastructure Insights應該用來識別主機的字元數。Data Infrastructure Insights僅對這麼長或更長的主機名稱執行 DNS 查找。
+
對於使用分隔符號的規則，輸入字串由分隔符號標記，並透過對相鄰標記進行幾種組合來建立主機名稱候選清單。然後對列表進行排序，從大到小。例如，對於 _vipsnq03_hba3_emc3_12ep0_ 的輸入鏈，清單將產生以下內容：

+
*** vipsnq03_hba3_emc3_12ep0
*** vipsnq03_hba3_emc3
*** hba3 emc3_12ep0
*** vipsnq03_hba3
*** emc3_12ep0
*** hba3_emc3
*** vipsnq03
*** 12ep0
*** emc3
*** hba3


** 使用正規表示式的規則需要正規表示式、格式和區分大小寫選擇。


. 按一下「*執行 AR*」以執行所有規則，或按一下按鈕中的向下箭頭以執行您建立的規則（以及自上次完整執行 AR 以來建立的任何其他規則）。
+
規則運行的結果顯示在*FC 識別*標籤中。





== 啟動自動設備解析度更新

設備解析度更新提交自上次全自動設備解析度運行以來新增的手動變更。運行更新可用於提交和運行對設備解析度配置所做的新手動輸入。沒有執行完整的設備解析運行。

.程式
. 登入Data Infrastructure InsightsWeb UI。
. 按一下“管理”>“裝置解析度”
. 在*裝置解析度*畫面中，按一下*執行 AR*按鈕中的向下箭頭。
. 點選“*更新*”開始更新。




== 規則輔助人工識別

此功能用於特殊情況，即您想要執行特定規則或規則清單（有或沒有一次性重新排序）來解析未知主機、儲存和磁帶裝置。

.開始之前
您有許多尚未識別的設備，並且還有多個成功識別其他設備的規則。


NOTE: 如果您的來源僅包含部分主機或裝置名稱，請使用正規表示式規則並格式化它以新增缺少的文字。

.程式
. 登入Data Infrastructure InsightsWeb UI。
. 按一下“管理”>“裝置解析度”
. 按一下“*光纖通道識別*”標籤。
+
系統顯示設備及其解析狀態。

. 選擇多個未識別的設備。
. 點擊*批次操作*並選擇*設定主機解析度*或*設定磁帶解析度*。
+
系統顯示識別螢幕，其中包含成功識別裝置的所有規則的清單。

. 將規則的順序變更為滿足您需求的順序。
+
規則的順序在識別畫面中發生了改變，但沒有全域改變。

. 選擇滿足您需求的方法。


Data Infrastructure Insights依照方法出現的順序執行主機解析過程，從頂部開始。

當遇到適用的規則時，規則名稱會顯示在規則列中並標識為手動。

有關的：link:task_device_resolution_fibre_channel.html["光纖通道設備解析"] link:task_device_resolution_ip.html["IP設備解析"] link:task_device_resolution_preferences.html["設定裝置解析度首選項"]
