---
sidebar: sidebar 
permalink: task_dc_ms_anf.html 
keywords: data collector, azure, Netapp files, anf 
summary: 設定Azure NetApp Files資料收集器。 
---
= 設定Azure NetApp Files資料收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights使用Azure NetApp Files資料收集器來取得庫存和效能資料。



== 要求

您需要以下資訊來設定此資料收集器。

* 連接埠需求：443 HTTPS
* Azure 管理 Rest IP (management.azure.com)
* Azure 服務主體用戶端 ID（使用者帳戶）
* Azure 服務主體驗證金鑰（使用者密碼）
* 您需要設定一個 Azure 帳戶來發現Data Infrastructure Insights。
+
一旦正確配置了帳戶並在 Azure 中註冊了應用程序，您將擁有使用Data Infrastructure Insights發現 Azure 執行個體所需的憑證。以下連結說明如何設定發現帳戶：



https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal[]



== 配置

根據下表將資料輸入資料收集器欄位：

[cols="2*"]
|===
| 場地 | 描述 


| Azure 服務主體用戶端 ID | Azure 登入 ID 


| Azure 租用戶 ID | Azure 租用戶 ID 


| Azure 服務主體驗證金鑰 | 登入認證金鑰 


| 我了解 Microsoft 會向我收取 API 請求費用 | 勾選此項目以驗證您是否瞭解 Microsoft 會針對 Insight 輪詢發出的 API 請求向您收費。 
|===


== 進階配置

[cols="2*"]
|===
| 場地 | 描述 


| 庫存輪詢間隔（分鐘） | 預設值為 60 
|===


== 故障排除

* ANF 資料收集器所使用的憑證必須能夠存取包含 ANF 磁碟區的任何 Azure 訂閱。
* 如果讀者存取導致效能收集失敗，請嘗試在資源群組層級授予貢獻者存取權限。


關於此數據收集器的更多信息，請參閱link:concept_requesting_support.html["支援"]頁面或在link:reference_data_collector_support_matrix.html["數據收集器支援矩陣"]。
