---
sidebar: sidebar 
permalink: task_dc_emc_powerstore.html 
keywords: data collector, PowerStore, EMC, DELL 
summary: 配置 DELL EMC PowerStore 資料收集器。 
---
= Dell EMC PowerStore 資料收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
EMC PowerStore 資料收集器從 EMC PowerStore 儲存收集庫存資訊。為了進行配置，資料收集器需要儲存處理器的 IP 位址以及只讀使用者名稱和密碼。

EMC PowerStore 資料收集器收集 PowerStore 在其他儲存陣列之間協調的捲到磁碟區的複製關係。Data Infrastructure Insights顯示每個 PowerStore 叢集的儲存陣列，並收集該叢集上的節點和儲存連接埠的庫存資料。未收集任何儲存池或磁碟區資料。



== 術語

Data Infrastructure Insights從該數據收集器獲取以下庫存資訊。對於Data Infrastructure Insights取得的每種資產類型，都會顯示用於該資產的最常用術語。當查看或排除此資料收集器的故障時，請記住以下術語：

[cols="2*"]
|===
| 供應商/型號術語 | Data Infrastructure Insights術語 


| 主持人 | 主持人 


| 主機磁碟區映射 | 主機磁碟區映射 


| 硬體（在“extra_details”物件下有磁碟機）：驅動器 | 磁碟 


| 器皿 | 儲存池 


| 簇 | 儲存陣列 


| 節點 | 儲存節點 


| fc_埠 | 港口 


| 體積 | 體積 


| 內部容積 | 檔案系統 
|===
注意：這些只是常見的術語映射，可能並不代表此資料收集器的所有情況。



== 要求

配置此數據收集器需要以下資訊：

* 儲存處理器的 IP 位址或完全限定域名
* 只讀使用者名稱和密碼




== 配置

[cols="2*"]
|===
| 場地 | 描述 


| PowerStore 網關 | PowerStore 儲存的 IP 位址或完全限定域名 


| 使用者名稱 | PowerStore 的使用者名稱 


| 密碼 | PowerStore 使用的密碼 
|===


== 進階配置

[cols="2*"]
|===
| 場地 | 描述 


| HTTPS 連接埠 | 預設值為 443 


| 庫存輪詢間隔（分鐘） | 庫存調查之間的間隔。預設值為 60 分鐘。 
|===
Cloud Insight 的 PowerStore 效能收集利用了 PowerStore 的 5 分鐘粒度來源資料。因此，Data Infrastructure Insights每五分鐘輪詢一次該數據，並且這是不可配置的。



== 故障排除

關於此數據收集器的更多信息，請參閱link:concept_requesting_support.html["支援"]頁面或在link:reference_data_collector_support_matrix.html["數據收集器支援矩陣"]。
