---
sidebar: sidebar 
permalink: task_dc_nutanix.html 
keywords: data collector, Nutanix, NX Series 
summary: 配置 Nutanix 資料收集器。 
---
= Nutanix NX 資料收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights使用 Nutanix 資料收集器來發現 Nutanix NX 儲存系統的庫存和效能資料。



== 術語

Data Infrastructure Insights從 Nutanix 數據收集器獲取以下庫存資訊。對於Data Infrastructure Insights取得的每種資產類型，都會顯示用於該資產的最常用術語。當查看或排除此資料收集器的故障時，請記住以下術語：

[cols="2*"]
|===
| 供應商/型號術語 | Data Infrastructure Insights術語 


| 儲存池 | 儲存池 


| Nutanix容器 | 內部體積 


| Nutanix容器 | 文件共享 


| NFS 分享 | 分享 
|===
注意：這些只是常見的術語映射，可能並不代表此資料收集器的所有情況。



== 要求

* 叢集的外部資料服務 IP 位址
* 只讀使用者名稱和密碼，除非正在使用 volume_groups，在這種情況下，需要管理員使用者名稱和密碼
* 連接埠要求：HTTPS 443




== 配置

[cols="2*"]
|===
| 場地 | 描述 


| Prism 外部 IP 位址 | 叢集的外部資料服務 IP 位址 


| 使用者名稱 | 管理員帳戶的使用者名稱 


| 密碼 | 管理者帳號的密碼 
|===


== 進階配置

[cols="2*"]
|===
| 場地 | 描述 


| TCP 連接埠 | 用於連接 Nutanix 陣列的 TCP 連接埠。預設值為 9440。 


| 庫存輪詢間隔（分鐘） | 庫存調查之間的間隔。預設值為 60 分鐘。 


| 效能輪詢間隔（秒） | 效能輪詢之間的間隔。預設值為 300 秒。 
|===


== 故障排除

關於此數據收集器的更多信息，請參閱link:concept_requesting_support.html["支援"]頁面或在link:reference_data_collector_support_matrix.html["數據收集器支援矩陣"]。
