---
sidebar: sidebar 
permalink: task_dc_na_storagegrid.html 
summary: 設定NetApp StorageGRID 資料收集器 
keywords: data collector, queries, create, storagegrid 
---
= NetApp StorageGRID 資料收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetApp StorageGRID 支援StorageGRID 從VMware支援從VMware組態收集庫存和效能。

[NOTE]
====
為了在所有StorageGRID系統中對 DII 權利進行一致的計量，無論底層硬體拓撲和配置如何， Data Infrastructure Insights都會使用總可用容量（storagegrid_storage_utilization_total_space_bytes），而不是基於實體磁碟佈局的 RAW 容量。

對於使用基於容量的授權模式的客戶， StorageGRID被計量為「物件」儲存。

對於使用傳統 (MU) 授權模式的客戶， StorageGRID以 40TiB 比 1 MU 的比率計量為二級儲存。

====


== 術語

Data Infrastructure Insights 會從 NetApp StorageGRID 收集器取得下列庫存資訊。對於所取得的每種資產類型、都會顯示此資產最常用的術語。檢視或疑難排解此資料收集器時、請謹記下列術語：

[cols="2*"]
|===
| 廠商/模型術語 | Data Infrastructure Insights 術語 


| StorageGRID | 儲存設備 


| 節點 | 節點 


| 租戶 | 儲存資源池 


| 鏟斗 | 內部Volume 
|===


== 需求

以下是設定此資料來源的需求：

* 主機IP位址StorageGRID
* 已指派「度量查詢」和「租戶存取」角色的使用者使用者名稱和密碼
* 連接埠 443




== 組態

[cols="2*"]
|===
| 欄位 | 說明 


| 主機IP位址StorageGRID | 管理VMware應用裝置的虛擬IP位址StorageGRID 


| 使用者名稱 | 用來登入StorageGRID 該應用程式的名稱 


| 密碼 | 用來登入StorageGRID 該應用程式的密碼 
|===


== 進階組態

[cols="2*"]
|===
| 欄位 | 說明 


| 庫存輪詢時間間隔（分鐘） | 預設為60分鐘 


| 效能意見調查時間間隔（秒） | 預設值為900秒 
|===


== 單一登入（SSO）

link:https://docs.netapp.com/sgws-112/index.jsp["StorageGRID"]韌體版本具有對應的 API 版本； 3.0 API 和更新版本支援單一登入（ SSO ）登入。

|===


| 韌體版本 | API 版本 | 支援單一登入（SSO） 


| 11.1 | 2 | 否 


| 11.2 | 3.0 | 是的 


| 11.5 | 3.3 | 是的 
|===


== 疑難排解

有關此資料收集器的其他資訊，請link:concept_requesting_support.html["支援"]link:reference_data_collector_support_matrix.html["資料收集器支援對照表"]參閱頁面或。
