---
sidebar: sidebar 
permalink: task_create_annotation_rules.html 
summary: 您可以建立註釋規則來自動將註釋套用到多個資產。 
keywords: annotate, annotation, rules 
---
= 建立註解規則
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用註解規則根據您定義的標準自動將註解套用到多個資產。Data Infrastructure Insights根據這些規則將註釋分配給資產。當 Cloud Insight 評估註解規則時，在單一資產頁面上手動設定的註解優先於基於規則的註解。

.開始之前
您必須已經為註釋規則建立了查詢。

.步驟
. 在Data Infrastructure Insights選單中點選*管理>註解規則*。
. 按一下「*+ 規則*」新增新的註解規則。
+
將顯示「新增規則」對話方塊。

. 執行以下操作：
+
.. 在「*名稱*」方塊中，輸入描述規則的唯一名稱。
+
該名稱出現在註解規則頁面中。

.. 點擊「查詢」並選擇Data Infrastructure Insights用來識別註釋適用的資產的查詢。
.. 點擊*註釋*並選擇要套用的註解。
.. 點擊“*值*”並為註釋選擇一個值。
+
例如，如果您選擇生日作為註釋，則您可以為該值指定一個日期。

.. 點選“儲存”
.. 如果您想立即執行所有規則，請按一下「執行所有規則」；否則，規則將按照定期安排的時間間隔運行。
+

NOTE: 在大型Data Infrastructure Insights環境中，您可能會注意到執行註解規則似乎需要一段時間才能完成。這是因為索引器首先運行，並且必須在運行規則之前完成。索引器使Data Infrastructure Insights能夠搜尋或過濾資料中的新物件或更新的物件和計數器。規則引擎等待索引器完成更新後再套用規則。







== 修改註解規則

您可以修改註解規則以變更規則的名稱、註解、註解的值或與規則關聯的查詢。

.步驟
. 在Data Infrastructure Insights選單中，按一下*管理>註解規則*。
+
註釋規則頁面顯示現有註釋規則的清單。

. 找到您想要修改的註解規則。
+
您可以透過在篩選方塊中輸入值來篩選註解規則，或按一下頁碼按頁瀏覽註解規則。

. 按一下要修改的規則的選單圖示。
. 點選“編輯”
+
將顯示「編輯規則」對話方塊。

. 修改註釋規則的名稱、註釋、值或查詢。




== 更改規則順序

註釋規則從規則清單的頂部到底部進行處理。若要變更規則的處理順序，請執行下列操作：

.步驟
. 按一下要移動的規則的選單圖示。
. 根據需要點擊*上移*或*下移*，直到規則出現在您想要的位置。


請注意，當執行多個規則來更新資產上的相同註釋時，第一個規則（從上到下運行）會套用註解並更新資產，然後第二個規則套用但不會更改前一個規則已經設定的任何註解。



== 刪除註解規則

您可能想要刪除不再使用的註解規則。

.步驟
. 在Data Infrastructure Insights選單中，按一下*管理>註解規則*。
+
註釋規則頁面顯示現有註釋規則的清單。

. 找到要刪除的註釋規則。
+
您可以透過在篩選方塊中輸入值來篩選註解規則，或按一下頁碼按頁瀏覽註解規則。

. 按一下要刪除的規則的選單圖示。
. 點擊“刪除”
+
系統會彈出確認訊息，詢問您是否要刪除該規則。

. 按一下“確定”

