---
sidebar: sidebar 
permalink: task_io_density_report_no_root.html 
summary: 當查詢高 I/O 密度時，您想要排除根卷。 
keywords: NetApp, root volume, high I/O, 
---
= 確保 IO 密度報告僅描述內部資料量
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetApp根磁碟區包含用於管理儲存系統的目錄和設定檔。當查詢高 I/O 密度時，您需要排除這些根卷。

當監控您的環境時，更重要的是確定哪些內部資料卷產生高 I/O 密度數字。為了準確地識別資料卷，您需要將NetApp內部卷與用於監控 I/O 密度的查詢隔離。

本指南介紹如何輕鬆識別NetApp根聚合、將其與內部磁碟區查詢的結果隔離，以及建立在將任何新的NetApp根聚合新增至系統時將其排除的規則。以下 Insight 功能用於確保您的 I/O 密度報告來自內部資料磁碟區：

* 建立一個查詢來識別 Insight 監控的所有NetApp根聚合。
* 每個NetApp根聚合都分配有一個註解。
* 建立註釋規則以將註釋套用至新的NetApp根聚合。


本指南中的步驟也可應用於其他供應商的儲存系統。您需要識別包含用於管理儲存系統的目錄和設定檔的捲，並使用類似的步驟排除這些卷。



== 建立查詢以識別NetApp根聚合

查詢根據使用者選擇的條件提供細粒度的搜尋。使用查詢，您可以搜尋租用戶中包含NetApp根聚合的內部磁碟區。

.步驟
. 建立查詢以識別租用戶上的NetApp根聚合：按一下 *查詢 > 新查詢 > 選擇資源類型*（？）
. 按一下“儲存池”
. 輸入根聚合的名稱
+
此範例使用“aggr0”作為名稱。建立聚合時，只需遵循以下名稱要求：

+
.. 它必須以字母或底線 (_) 開頭。
.. 它只能包含字母、數字和底線。
.. 其長度不得超過 250 個字元。在大多數情況下，聚合的名稱是 aggr0、aggr_0 或類似的名稱。可能需要一個迭代過程來識別租戶上的所有NetApp根聚合。


. 點擊“*儲存*”並輸入新查詢的名稱。
+
如前所述，這可能是一個迭代過程，需要多個查詢才能識別所有NetApp根聚合。





== 為查詢傳回的根磁碟區建立註釋

註釋是您分配給資產的專門註釋，允許您透過註釋過濾資產。您建立的註釋將用於識別租用戶上的NetApp根聚合，並確保它們不包含在特定報告中。

.開始之前
您必須已確定要從「高 I/O 密度」報告中排除的所有根聚合。

.步驟
. 在“Data Infrastructure Insights”功能表中，按一下“管理”>“註釋”
. 點擊“新增”
+
.. 輸入註解的名稱：*RootAggr*
.. 輸入註解的描述：*從「高 I/O 密度」報告中刪除根聚合*
.. 輸入註解類型：*布林值*


. 點選“儲存”




== 建立註釋規則以自動從 I/O 密度報表中排除特定聚合

作為手動將註釋應用於單一資產的替代方法，您可以使用註釋規則自動將註釋套用至多個資產。註釋規則是基於您建立的查詢，當在系統上執行時，它們會將新資產新增至現有資產集中。當這些資產集從報告中排除時，新資產也會自動被排除。

.開始之前
您必須已建立並儲存查詢，該查詢可識別您在租用戶上識別的NetApp根聚合。

.步驟
. 在Data Infrastructure Insights工具列中，按一下*管理>註解規則*。
. 按一下“*新增*”。將顯示「新增規則」對話方塊。
+
.. 在名稱方塊中，輸入描述規則的唯一名稱：*「RootAggrExclude」*
.. 按一下查詢並選擇 Insight 應該用來套用註解規則的查詢：*「Aggregate0」*
.. 點擊註解並選擇：“Root agg exclude”
.. 點擊“值”並輸入“True”



