---
sidebar: sidebar 
permalink: task_create_application.html 
summary: 您可以視需要定義應用程式、然後套用至環境中的資產。 
keywords: application, create application, 
---
= 建立應用程式
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
若要追蹤與環境中執行的特定應用程式相關的資料、您可以在 Data Infrastructure Insights 中定義應用程式。

.開始之前
如果您想要將應用程式與企業實體建立關聯、則必須先建立企業實體、才能定義應用程式。

.關於這項工作
Data Infrastructure Insights 可讓您追蹤與應用程式相關的資產資料、以利使用或成本報告等工作。

.步驟
. 在 Data Infrastructure Insights 功能表中、按一下 * 可觀察性 > 豐富 > 應用程式 * 。選取
+
此時會顯示「新增應用程式」對話方塊。

. 輸入應用程式的唯一名稱。
. 選取應用程式的優先順序。
. 按一下「 * 儲存 * 」。


定義應用程式之後、即可將其指派給資產。



== 將應用程式指派給資產

此程序將應用程式指派給主機做為範例。您可以將主機、虛擬機器、磁碟區或內部磁碟區指派給應用程式。

.步驟
. 找出您要指派給應用程式的資產：
. 按一下*查詢>+新查詢*、然後搜尋主機。
. 按一下要與應用程式建立關聯之主機左側的核取方塊。
. 按一下*大量動作>新增應用程式*。
. 選取您要指派資產的應用程式。


您指派的任何新應用程式、都會覆寫從其他資產衍生的資產上的任何應用程式。例如、磁碟區會從主機繼承應用程式、當新的應用程式指派給磁碟區時、新的應用程式會優先於衍生的應用程式。


NOTE: 對於具有大量相關資產的環境、將應用程式指派繼承至這些資產可能需要數分鐘的時間。如果您擁有許多相關資產、請留出更多時間進行繼承。

.完成後
將主機指派給應用程式之後、您可以將其餘資產指派給應用程式。若要存取應用程式的登陸頁面、請按一下*管理>應用程式*、然後選取您建立的應用程式。
