---
sidebar: sidebar 
permalink: task_dc_ibm_powervm.html 
keywords: IBM, powerVM, 
summary: 配置 IBM PowerVM 資料收集器。 
---
= 配置 IBM PowerVM 資料收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
IBM PowerVM (SSH) 資料收集器用於收集由硬體管理控制台 (HMC) 管理的 IBM POWER 硬體實例上執行的虛擬分區的資訊。



== 術語

Data Infrastructure Insights從 IBM POWER 硬體實例上執行的虛擬分區取得庫存資訊。對於所取得的每種資產類型，都會顯示該資產最常用的術語。當查看或排除此資料收集器的故障時，請記住以下術語：

[cols="2*"]
|===
| 供應商/型號術語 | Data Infrastructure Insights術語 


| 硬碟 | 虛擬磁碟 


| 管理系統 | 主持人 


| LPAR、VIO 伺服器 | 虛擬機 


| 卷組 | 資料儲存 


| 物理體積 | 邏輯單元號 
|===
注意：這些只是常見的術語映射，可能並不代表此資料收集器的所有情況。



== 要求

配置和使用此資料收集器必須滿足以下要求：

* 硬體管理控制台 (HMC) 的 IP 位址
* 透過 SSH 存取硬體管理控制台 (HMC) 的使用者名稱和密碼
* 連接埠要求 SSH-22
* 所有管理系統和邏輯分割區安全域的檢視權限
+
使用者還必須具有查看 HMC 配置的權限以及收集 HMC 控制台安全分組的 VPD 資訊的能力。還必須允許使用者在邏輯分區安全性群組下存取虛擬 IO 伺服器命令。最佳做法是從操作員的角色開始，然後刪除所有角色。  HMC 上的唯讀使用者沒有在 AIX 主機上執行代理命令的權限。

* IBM 的最佳實務是讓兩個或多個 HMC 監控設備。請注意，這可能會導致OnCommand Insight報告重複的設備，因此強烈建議將冗餘設備新增至此資料收集器的高級配置中的「排除設備」清單。




== 配置

[cols="2*"]
|===
| 場地 | 描述 


| 硬體管理控制台 (HMC) IP 位址 | PowerVM 硬體管理控制台的 IP 位址或完全限定域名 


| HMC 用戶 | 硬體管理控制台的使用者名 


| 密碼 | 用於硬體管理控制台的密碼 
|===


== 進階配置

[cols="2*"]
|===
| 場地 | 描述 


| 庫存輪詢間隔（分鐘） | 庫存調查之間的間隔。預設值為 20 分鐘。 


| SSH 連接埠 | 用於 SSH 到 PowerVM 的端口 


| 密碼 | 用於硬體管理控制台的密碼 


| 重試次數 | 庫存重試次數 


| 排除設備 | 要排除的裝置 ID 或顯示名稱的逗號分隔列表 
|===


== 故障排除

關於此數據收集器的更多信息，請參閱link:concept_requesting_support.html["支援"]頁面或在link:reference_data_collector_support_matrix.html["數據收集器支援矩陣"]。
