---
sidebar: sidebar 
permalink: task_dc_na_ontap_rest.html 
keywords: data collector, ontap, ontap, CDOT, REST 
summary: ONTAP REST Data Collector 
---
= NetApp ONTAP REST 資料收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
此資料收集器會使用 REST API 呼叫、從執行 ONTAP 9.14.1 及更高版本的儲存系統擷取庫存、 EMS 記錄和效能資料。對於舊版 ONTAP 系統、請使用 ZAPI 型的「 NetApp ONTAP 資料管理軟體」收集器類型。


NOTE: ONTAP REST 收集器可用來取代先前的 ONTAPI 型收集器。因此、收集或報告的計量可能會有所差異。如需關於 ONTAPI 與 REST 之間差異的詳細資訊，請參閱link:https://docs.netapp.com/us-en/ontap-restmap-9141/index.html["ONTAP 9.14.1 ONTAPI- 對 REST 的對應"]文件。



== 需求

以下是設定及使用此資料收集器的需求：

* 您必須具有所需存取層級的使用者帳戶存取權。請注意、如果建立新的 REST 使用者 / 角色、則需要管理員權限。
+
** 在功能上、 Data Infrastructure Insights 主要會提出讀取要求、但資料基礎架構 Insights 需要一些寫入權限才能向 ONTAP 陣列註冊。請參閱下面的 _ 權限注意事項 _ 。


* ONTAP 9.14.1 版或更新版本。
* 連接埠需求： 443




== 權限相關注意事項

由於許多 Data Infrastructure Insights 的 ONTAP 儀表板仰賴進階 ONTAP 計數器、因此您應該在資料收集器進階組態區段中保持 * 啟用進階計數器資料收集 * 。

若要在叢集層級建立 Data Infrastructure Insights 的本機帳戶、請使用叢集管理管理員使用者名稱 / 密碼登入 ONTAP 、然後在 ONTAP 伺服器上執行下列命令：

. 開始之前、您必須先以ONTAP _Administrator帳戶登入到VMware、然後才能啟用_diagnostic-level命令_。
. 擷取類型為 _admin_ 的虛擬伺服器名稱。您將在後續命令中使用此名稱。
+
 vserver show -type admin
. 使用下列命令建立角色：
+
....
security login rest-role create -role {role name} -api /api -access readonly
security login rest-role create -role {role name} -api /api/cluster/agents -access all
vserver services web access create -name spi -role {role name} -vserver {vserver name as retrieved above}
....
. 使用下列命令建立唯讀使用者。執行create命令後、系統會提示您輸入此使用者的密碼。請注意，在下列命令中，我們會顯示角色集為 _CI_readonly_ 。如果您在上述步驟 3 中建立的角色名稱不同，請改用該自訂角色名稱。


 security login create -user-or-group-name {username} -application http -authentication-method password -role {role name}
如果使用AD/LDAP帳戶、則命令應該是

 security login create -user-or-group-name DOMAIN\aduser/adgroup -application http -authentication-method domain -role ci_readonly
產生的角色和使用者登入內容如下。實際輸出可能有所不同：

[listing]
----
security login rest-role show -vserver <vserver name> -role restRole

               Role                                    Access
Vserver        Name            API                     Level
----------     -------------   -------------------     ------
<vserver name> restRole        /api                    readonly
                               /api/cluster/agents     all
2 entries were displayed.

security login show -vserver <vserver name> -user-or-group-name restUser

Vserver: <vserver name>
                                                                 Second
User/Group                 Authentication                 Acct   Authentication
Name           Application Method        Role Name        Locked Method
-------------- ----------- ------------- ---------------- ------ --------------
restUser       http        password      restRole         no     none
----


== 移轉

若要從先前的 ONTAP （ ontapi ）資料收集器移轉至較新的 ONTAP REST 收集器、請執行下列步驟：

. 新增 REST Collector 。建議您輸入不同於先前收集器所設定使用者的資訊。例如、請使用上方「權限」一節中註明的使用者。
. 暫停先前的收集器、使其不會繼續收集資料。
. 讓新的 REST 收集器擷取資料至少 30 分鐘。在此期間忽略任何「正常」的資料。
. 休息期間過後、當 REST 收集器繼續擷取時、您應該會看到資料穩定。


您可以視需要使用相同程序返回先前的收集器。



== 組態

[cols="2*"]
|===
| 欄位 | 說明 


| ONTAP 管理 IP 位址 | NetApp 叢集的 IP 位址或完整網域名稱。必須是叢集管理 IP/FQDN 。 


| ONTAP REST 使用者名稱 | NetApp叢集的使用者名稱 


| ONTAP REST 密碼 | NetApp叢集的密碼 
|===


== 進階組態

[cols="2*"]
|===
| 欄位 | 說明 


| 庫存輪詢時間間隔（分鐘） | 預設為60分鐘。 


| 效能意見調查時間間隔（秒） | 預設為 60 秒。 


| 進階計數器資料收集 | 選取此選項可在ONTAP 輪詢中包含「功能先進的計數器」資料。預設為啟用。 


| 啟用 EMS 事件收集 | 選取此選項以納入 ONTAP EMS 記錄事件資料。預設為啟用。 


| EMS 輪詢時間間隔（秒） | 預設為 60 秒。 
|===


== 術語

Data Infrastructure Insights 會從 ONTAP 資料收集器擷取庫存、記錄和效能資料。對於所取得的每種資產類型、都會顯示該資產最常用的術語。檢視或疑難排解此資料收集器時、請謹記下列術語：

[cols="2*"]
|===
| 廠商/模型術語 | Data Infrastructure Insights 術語 


| 磁碟 | 磁碟 


| RAID群組 | 磁碟群組 


| 叢集 | 儲存設備 


| 節點 | 儲存節點 


| Aggregate | 儲存資源池 


| LUN | Volume 


| Volume | 內部Volume 


| 儲存虛擬機器 /Vserver | 儲存虛擬機器 
|===


== 資料管理術語ONTAP

下列詞彙適用於ONTAP 您在《支援資料管理》儲存資產登陸頁面上可能找到的物件或參考資料。其中許多術語也適用於其他資料收集器。



=== 儲存設備

* 模型–此叢集內唯一、獨立節點模型名稱的以逗號分隔的清單。如果叢集內的所有節點都是相同的模型類型、則只會顯示一個模型名稱。
* 廠商–如果您要設定新的資料來源、您會看到相同的廠商名稱。
* 序號–陣列 UUID
* IP–通常是在資料來源中設定的IP或主機名稱。
* 微碼版本–韌體。
* 原始容量：系統中所有實體磁碟的基礎2總和、無論其角色為何。
* 延遲：代表主機面對的工作負載在讀取和寫入過程中所經歷的情況。在理想情況下、 Data Infrastructure Insights 會直接取得這項價值、但通常情況並非如此。資料基礎架構 Insights 通常會執行從個別內部磁碟區統計資料衍生的 IOPs 加權計算、而不是提供這項功能的陣列。
* 處理量：從內部磁碟區集合而來。管理：這可能包含裝置管理介面的超連結。由 Data Infrastructure Insights 資料來源以程式設計方式建立、作為庫存報告的一部分。




=== 儲存資源池

* 儲存設備：此資源池所使用的儲存陣列。必填。
* 類型–從列舉的可能性清單清單中選取一個描述性值。最常見的是「Aggregate」或「RAID Group」。
* 節點–如果此儲存陣列的架構使集區屬於特定儲存節點、則其名稱將會顯示在這裡、以超連結的形式連結至其自己的登陸頁面。
* 使用Flash Pool–是/否值–此SATA / SAS型集區是否使用SSD進行快取加速？
* 備援：RAID層級或保護方案。RAID-DP為雙同位元檢查、RAID_tp為三同位元檢查。
* 容量：此處的值是已用邏輯容量、可用容量和邏輯總容量、以及這些容量使用的百分比。
* 過度委派容量：如果使用效率技術、您已將容量或內部Volume容量的總和分配給大於儲存資源池邏輯容量的總和、則此處的百分比值將大於0%。
* Snapshot–已使用的快照容量和總容量、如果您的儲存資源池架構將部分容量專用於專為快照而設計的區段區域。在不支援支援的情況下、支援的部分可能會出現這個問題、而其他的不支援的組態則較少。ONTAP MetroCluster ONTAP
* 使用率–百分比值、顯示此儲存資源池中任何磁碟貢獻容量的最高磁碟使用率百分比。磁碟使用率不一定與陣列效能有密切的關聯、因為磁碟重建、重複資料刪除活動等原因、在缺乏主機驅動的工作負載的情況下、使用率可能會很高。此外、許多陣列的複寫實作可能會提高磁碟使用率、但不會顯示為內部磁碟區或磁碟區工作負載。
* IOPS：所有磁碟的IOPs總和、可為此儲存資源池提供容量。處理量：所有磁碟的總處理量、可為此儲存資源池提供容量。




=== 儲存節點

* 儲存設備：此節點屬於何種儲存陣列。必填。
* HA合作夥伴：在節點將容錯移轉至一個節點、而只有一個節點的平台上、通常會顯示於此處。
* 狀態–節點健全狀況。只有當陣列健全狀況足以由資料來源進行庫存時、才能使用。
* 模型–節點的模型名稱。
* 版本–裝置的版本名稱。
* 序號–節點序號。
* 記憶體：基礎2記憶體（若有）。
* 使用率：ONTAP 在功能方面、這是專屬演算法的控制器壓力索引。每次效能意見調查都會報告0到100%之間的數字、這是WAFL 指較高的VMware磁碟爭用或平均CPU使用率。如果您觀察到持續值> 50%、這表示規模過小–可能是控制器/節點不夠大、或旋轉磁碟不足以吸收寫入工作負載。
* IOPS –直接衍生自節點物件上的 ONTAP REST 通話。
* 延遲–直接衍生自節點物件上的 ONTAP REST 通話。
* 處理量–直接衍生自節點物件上的 ONTAP REST 通話。
* 處理器–CPU數。




== ONTAP 電力指標

數種 ONTAP 模式提供資料基礎架構洞見的電力指標、可用於監控或警示。下列支援和不支援的機型清單並不完整、但應提供一些指引；一般而言、如果機型與清單上的機型屬於同一個系列、則支援應該相同。

支援的機型：

A200 A220 A250 A300 A320 A400 A700 A700 A800 A900 C190 FAS2240-4 FAS2552 FAS2650 FAS2720 FAS2750 FAS8200 FAS8300 FAS8700 FAS9000

不支援的機型：

FAS2620 FAS3250 FAS3270 FAS500f FAS6280 FAS / AFF 8020 FAS / AFF 8040 FAS / AFF 8060 FAS / AFF 8080



== 疑難排解

如果您在使用此資料收集器時遇到問題、請嘗試下列事項：

[cols="2*"]
|===
| 問題： | 試用： 


| 嘗試建立 ONTAP REST 資料收集器時，會出現如下錯誤：組態： 10.193.70.14 ： ONTAP REST API 位於 10.193.70.14 ，無法使用： 10.193.70.14 無法取得 /API/cluster ： 400 錯誤要求 | 這可能是因為使用了一種老舊的 ONTAP 陣列、例如 ONTAP 9.6 ）、而該陣列沒有 REST API 功能。ONTAP 9.14.1 是 ONTAP REST 收集器支援的最低 ONTAP 版本。在預先休息的 ONTAP 版本中、應會有「 400 不良要求」回應。對於支援 REST 但不支援 9.14.1 或更新版本的 ONTAP 版本，您可能會看到下列 simillar 訊息：組態： 10.193.98.84 ： ONTAP REST API 10.193.98.84 不可用： 10.193.98.84 ： ONTAP REST API 10.193.98.84 可提供： cheryl5-cluster 2 9.10.1 a3c247-3c3c~9.50b3c3 。 


| 我看到 ONTAP ontapi 收集器顯示資料的空白或「 0 」指標。 | ONTAP REST 不會報告僅在 ONTAP 系統內部使用的度量。例如、 ONTAP REST 不會收集系統集合體、只會收集 SVM 的「資料」類型。其他 ONTAP REST 計量範例可能會報告零或空白資料： InternalVolumes ： REST 不再報告 vol0 。Aggregate ： REST 不再報告 aggr0 。儲存設備：大部分的指標都是內部 Volume 指標的彙總套件、因此會受到上述影響。儲存虛擬機器： REST 不再報告除 'data' 以外的 SVM 類型（例如「叢集」、「 GMT 」、「節點」）。您也可能會注意到、由於預設效能輪詢期間從 15 分鐘變更為 5 分鐘、因此具有資料的圖形外觀也會有所變更。更頻繁的輪詢意味著需要繪製更多資料點。 
|===
您可以在頁面或中找到其他link:concept_requesting_support.html["支援"]link:reference_data_collector_support_matrix.html["資料收集器支援對照表"]資訊。
