---
sidebar: sidebar 
permalink: task_query_assign_multiple_applications.html 
summary: 使用查詢為物件指派多個應用程式或註釋，或從物件中刪除多個應用程式或註釋。 
keywords: query, queries, application, annotation, multiple 
---
= 將多個應用程式指派給資產或從資產中刪除多個應用程式
:hardbreaks:
:allow-uri-read: 


[role="lead"]
您可以分配多個link:task_create_application.html["應用程式"]使用查詢從資產中新增或刪除多個應用程序，而不必手動分配或刪除它們。


NOTE: 您可以按照以下步驟新增或刪除link:task_defining_annotations.html["註解"]以同樣的方式。

.開始之前
您必須已經建立了一個查詢來尋找您要編輯的所有資產。

.步驟
. 點擊“*探索*”並選擇“*指標查詢*”。
+
顯示查詢頁面。

. 按一下尋找資產的查詢的名稱。
+
顯示與查詢相關的資產清單。

. 在清單中選擇所需的資產或按一下頂部複選框以選擇全部。
+
顯示批次操作下拉選單。

. 若要將應用程式新增至選定的資產，請按一下「批次操作」並選擇「新增應用程式」。
. 選擇一個或多個應用程式。
+
您可以為主機、內部磁碟區、qtree 和虛擬機器選擇多個應用程式；但是，您只能為一個磁碟區或共用選擇一個應用程式。

. 點選“儲存”。
. 若要刪除已指派給資產的應用程序，請按一下“批次操作”並選擇“*刪除應用程式*”。
. 選擇要刪除的一個或多個應用程式。
. 按一下“*刪除*”。


您指派的任何新應用程式都會覆寫該資產上從其他資產派生的任何應用程式。例如，磁碟區從主機繼承應用程序，當新應用程式分配給磁碟區時，新應用程式優先於派生的應用程式。

在批次新增操作中按一下「儲存」或在批次刪除操作中按一下「刪除」後，Data Infrastructure Insights會通知您該操作將需要一些時間。您可以忽略此訊息；操作將在背景繼續。


NOTE: 對於具有大量相關資產的環境，將應用程式指派繼承到這些資產可能需要幾分鐘。如果您擁有許多相關資產，請留出更多時間進行繼承。
