---
sidebar: sidebar 
permalink: task_dc_emc_recoverpoint.html 
keywords: data collector, RecoverPoint, EMC, DELL 
summary: 設定Dell EMC RecoverPoint資料收集器。 
---
= Dell EMC RecoverPoint資料收集器
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
EMC RecoverPoint資料收集器的主要使用案例是探索RecoverPoint儲存設備所促進的磁碟區對磁碟區複寫關係。此收集器也會探索RecoverPoint應用裝置本身。請注意、Dell/EMC銷售的VMware VM備份解決方案「VM的RecoverPoint」不受此收集器支援

對於組態、資料收集器需要儲存處理器的IP位址、以及唯讀使用者名稱和密碼。

EMC RecoverPoint資料收集器會收集RecoverPoint在其他儲存陣列之間協調的磁碟區對磁碟區複寫關係。Data Infrastructure Insights 會顯示每個 RecoverPoint 叢集的儲存陣列、並收集該叢集上節點和儲存連接埠的庫存資料。不會收集儲存資源池或Volume資料。



== 需求

設定此資料收集器需要下列資訊：

* 儲存處理器的IP位址或完整網域名稱
* 唯讀使用者名稱和密碼
* 透過連接埠443進行REST API存取




== 組態

[cols="2*"]
|===
| 欄位 | 說明 


| RecoverPoint的位址 | RecoverPoint叢集的IP位址或完整網域名稱 


| 使用者名稱 | RecoverPoint叢集的使用者名稱 


| 密碼 | RecoverPoint叢集使用的密碼 
|===


== 進階組態

[cols="2*"]
|===
| 欄位 | 說明 


| TCP 連接埠 | 用於連線至RecoverPoint叢集的TCP連接埠 


| 庫存輪詢時間間隔（分鐘） | 庫存輪詢之間的時間間隔。預設值為 20 分鐘。 


| 排除的叢集 | 輪詢時要排除的叢集ID或名稱清單、以逗號分隔。 
|===


== 疑難排解

有關此資料收集器的其他資訊，請link:concept_requesting_support.html["支援"]link:reference_data_collector_support_matrix.html["資料收集器支援對照表"]參閱頁面或。
