---
sidebar: sidebar 
permalink: task_dc_emc_ecs.html 
keywords: data collector, ecs, EMC 
summary: 配置 ECS 資料收集器。 
---
= 配置 EMC ECS 資料收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
此資料收集器從 EMC ECS 儲存系統取得庫存和效能資料。對於配置，資料收集器需要 ECS 叢集的 IP 位址或主機名稱以及使用者名稱和密碼。


NOTE: Dell EMC ECS 依照不同的原始 TB 與託管單位費率進行計量。每 40TB 未格式化 ECS 容量按 1link:concept_subscribing_to_cloud_insights.html#pricing["管理單元（MU）"] 。



== 術語

Data Infrastructure Insights從 ECS 數據收集器獲取以下庫存資訊。對於所取得的每種資產類型，都會顯示用於該資產的最常用術語。當查看或排除此資料收集器的故障時，請記住以下術語：

[cols="2*"]
|===
| 供應商/型號術語 | Data Infrastructure Insights術語 


| 簇 | 儲存 


| 租戶 | 儲存池 


| 桶 | 內部體積 


| 磁碟 | 磁碟 
|===
注意：這些只是常見的術語映射，可能並不代表此資料收集器的所有情況。



== 要求

* ECS 叢集的 IP 位址或主機名
* ECS 系統的使用者名稱和密碼
* 端口 4443 (HTTPS)。需要與 ECS 系統上的 TCP 連接埠 4443 建立出站連線。




== 配置

[cols="2*"]
|===
| 場地 | 描述 


| ECS 主機 | ECS 系統的 IP 位址或完全限定域名 


| ECS 主機連接埠 | 與 ECS 主機通訊所使用的連接埠 


| ECS 使用者 ID | ECS 的使用者 ID 


| 密碼 | ECS使用的密碼 
|===


== 進階配置

[cols="2*"]
|===
| 場地 | 描述 


| 庫存輪詢間隔（分鐘） | 預設值為 360 分鐘。 
|===


== 故障排除

如果您在使用此資料收集器時遇到問題，請嘗試以下操作：



=== 存貨

[cols="2*"]
|===
| 問題： | 試試一下： 


| 錯誤：使用者身份驗證失敗。 | 確保您對此裝置的憑證正確無誤。 
|===


=== 表現

[cols="2*"]
|===
| 問題： | 試試一下： 


| 錯誤：未收集足夠的數據。 | * 檢查日誌檔案中的收集時間戳記並相應地修改輪詢間隔 * 等待更長時間 


| 錯誤：效能輪詢間隔太大。 | 檢查日誌檔案 ${logfile} 中的收集時間戳記並相應地修改輪詢間隔 
|===
更多資訊可從link:concept_requesting_support.html["支援"]頁面或在link:reference_data_collector_support_matrix.html["數據收集器支援矩陣"]。
