---
sidebar: sidebar 
permalink: task_dc_emc_datadomain.html 
keywords: data collector, Data Domain, EMC, DELL 
summary: 配置 DELL EMC Data Domain 資料收集器。 
---
= DELL EMC Data Domain 資料收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
此資料收集器從 DELL EMC Data Domain 重複資料刪除儲存系統收集庫存和效能資訊。若要設定此資料收集器，您必須遵循特定的配置說明和使用建議。



== 術語

Data Infrastructure Insights從 Data Domain 資料收集器取得以下庫存資訊。對於Data Infrastructure Insights取得的每種資產類型，都會顯示用於該資產的最常用術語。當查看或排除此資料收集器的故障時，請記住以下術語：

[cols="2*"]
|===
| 供應商/型號術語 | Data Infrastructure Insights術語 


| 磁碟 | 磁碟 


| 大批 | 儲存 


| FC埠 | 港口 


| 檔案系統 | 內部體積 


| 配額 | 配額 


| NFS 和 CIFS 共享 | 文件共享 
|===
注意：這些只是常見的術語映射，可能並不代表該資料收集器的所有情況。



== 要求

您需要以下資訊來設定此資料收集器：

* Data Domain 設備的 IP 位址
* Data Domain 儲存的唯讀使用者名稱和密碼
* SSH 連接埠 22




== 配置

[cols="2*"]
|===
| 場地 | 描述 


| IP 位址 | Data Domain 儲存陣列的 IP 位址或完全限定域名 


| 使用者名稱 | Data Domain 儲存陣列的使用者名 


| 密碼 | Data Domain 儲存陣列的密碼 
|===


== 進階配置

[cols="2*"]
|===
| 場地 | 描述 


| 庫存輪詢間隔（分鐘） | 庫存調查之間的間隔。預設值為 20。 


| SSH 連接埠 | SSH服務埠 
|===


== 故障排除

關於此數據收集器的更多信息，請參閱link:concept_requesting_support.html["支援"]頁面或在link:reference_data_collector_support_matrix.html["數據收集器支援矩陣"]。
