---
sidebar: sidebar 
permalink: task_dc_oracle_zfs.html 
keywords: data collector, Oracle, ZFS, storage applicance 
summary: 配置 Oracle ZFS 資料收集器。 
---
= Oracle ZFS 儲存設備資料收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights使用 Oracle ZFS 儲存設備資料收集器來收集庫存和效能資料。



== 術語

Data Infrastructure Insights使用 Oracle ZFS 資料收集器取得庫存資訊。對於Data Infrastructure Insights取得的每種資產類型，都會顯示用於該資產的最常用術語。當查看或排除此資料收集器的故障時，請記住以下術語：

[cols="2*"]
|===
| 供應商/型號術語 | Data Infrastructure Insights術語 


| 磁碟（SSD） | 磁碟 


| 簇 | 儲存 


| 控制器 | 儲存節點 


| 邏輯單元號 | 體積 


| LUN 映射 | 體積圖 


| 發起者，目標 | 體積遮罩 


| 分享 | 內部體積 
|===
注意：這些只是常用術語映射，可能並不代表此資料來源的所有情況。



== 要求

* ZFS Controller-1 和 ZFS Controller-2 的主機名
* 管理員使用者名稱和密碼
* 連接埠需求：215 HTTP/HTTPS




== 所需績效指標

Oracle ZFS 設備為儲存管理員提供了很大的靈活性來擷取效能統計資料。Data Infrastructure Insights希望您將高可用性對中的每個控制器配置為擷取以下指標：

* smb2.ops[分享]
* nfs3.ops[分享]
* nfs4.ops[分享]
* nfs4-1.ops[分享]


如果控制器無法擷取其中的任何一個或全部，則可能會導致Data Infrastructure Insights沒有或少報「內部磁碟區」上的工作負載。



== 配置

[cols="2*"]
|===
| 場地 | 描述 


| ZFS 控制器-1 主機名 | 儲存控制器 1 的主機名 


| ZFS 控制器-2 主機名 | 儲存控制器 2 的主機名 


| 使用者名稱 | 儲存系統管理員使用者帳戶的使用者名 


| 密碼 | 管理者用戶帳號的密碼 
|===


== 進階配置

[cols="2*"]
|===
| 場地 | 描述 


| 連接類型 | HTTPS 或 HTTP，也顯示預設端口 


| 覆蓋連接埠 | 如果為空，則在連接類型欄位中使用預設端口，否則輸入要使用的連接端口 


| 庫存輪詢間隔 | 預設值為 60 秒 


| 效能輪詢間隔（秒） | 預設值為 300。 
|===


== 故障排除

如果您在使用此資料收集器時遇到問題，請嘗試以下操作：



=== 存貨

[cols="2a, 2a"]
|===
| 問題： | 試試一下： 


 a| 
“登入憑證無效”
 a| 
驗證 Zfs 使用者帳號和密碼



 a| 
“請求失敗，狀態為 404 \https://.....:215/api/access/v1”
 a| 
您的 ZFS 陣列可能太舊，無法支援 REST API。  AK 2013.1.3.0 是第一個支援 REST API 的 ZFS OS 版本，並非所有 ZFS 裝置都可以升級到它。



 a| 
“配置錯誤”，錯誤訊息為“REST 服務已停用”
 a| 
驗證此裝置上是否啟用了 REST 服務。



 a| 
“配置錯誤”，錯誤訊息為“使用者未授權執行命令”
 a| 
此錯誤可能是由於配置的使用者未包含某些角色（例如“advanced_analytics”）。

對具有唯讀角色的使用者套用分析範圍可能會消除該錯誤。請依照以下步驟操作：

. 在 ZFs 系統上，從配置 -> 使用者螢幕，將滑鼠移到角色上並雙擊以允許編輯
. 從範圍下拉選單中選擇“分析”。出現可能的屬性清單。
. 點擊最頂部的複選框，它將選擇所有三個屬性。
. 點選右側的新增按鈕。
. 點擊彈出視窗右上角的應用程式按鈕。彈出視窗將會關閉。


|===
更多資訊可從link:concept_requesting_support.html["支援"]頁面或在link:reference_data_collector_support_matrix.html["數據收集器支援矩陣"]。
