---
sidebar: sidebar 
permalink: task_dc_emc_scaleio.html 
keywords: data collector, scaleIO, PowerFlex EMC, DELL 
summary: 配置 DELL EMC ScaleIO/PowerFlex 資料收集器。 
---
= DELL EMC ScaleIO/PowerFlex 資料收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
ScaleIO/PowerFlex 資料收集器從 ScaleIO 和 PowerFlex 儲存收集庫存資訊。為了進行配置，此資料收集器需要 ScaleIO/PowerFlex 網關位址以及管理員使用者名稱和密碼。



== 術語

Data Infrastructure Insights從 ScaleIO/PowerFlex 資料收集器取得以下庫存資訊。對於Data Infrastructure Insights取得的每種資產類型，都會顯示用於該資產的最常用術語。當查看或排除此資料收集器的故障時，請記住以下術語：

[cols="2*"]
|===
| 供應商/型號術語 | Data Infrastructure Insights術語 


| MDM（元資料管理器）集群 | 儲存 


| SDS（​​ScaleIO/PowerFlex 資料伺服器） | 儲存節點 


| 儲存池 | 儲存池 


| 體積 | 體積 


| 裝置 | 磁碟 
|===
注意：這些只是常見的術語映射，可能並不代表此資料收集器的所有情況。



== 要求

* 對管理員使用者帳戶的唯讀存取權限
* 連接埠需求：HTTPS 連接埠 443




== 配置

[cols="2*"]
|===
| 場地 | 描述 


| ScaleIO/PowerFlex 網關 | ScaleIO/PowerFlex 閘道的 IP 位址或 FQDN，以逗號 (,) 或分號 (;) 分隔 


| 使用者名稱 | 用於登入 ScaleIO/PowerFlex 設備的管理員使用者名稱 


| 密碼 | 用於登入 ScaleIO/PowerFlex 設備的密碼 
|===


== 進階配置

按一下「庫存」複選框以啟用庫存收集。

[cols="2*"]
|===
| 場地 | 描述 


| HTTPS 連接埠 | 443 


| 庫存輪詢間隔（分鐘） | 預設值為 60。 


| 連接逾時（秒） | 預設值為 60。 
|===


== 故障排除

更多資訊可從link:concept_requesting_support.html["支援"]頁面或在link:reference_data_collector_support_matrix.html["數據收集器支援矩陣"]。
