---
sidebar: sidebar 
permalink: task_query_assign_multiple_applications.html 
summary: 使用查詢來指派多個應用程式或註釋給物件、或從物件移除多個應用程式或註釋。 
keywords: query, queries, application, annotation, multiple 
---
= 將多個應用程式指派給資產、或從資產中移除多個應用程式
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
您可以使用查詢將多個應用程式指派給或移除資產中的多link:task_create_application.html["應用程式"]個應用程式，而不必手動指派或移除這些應用程式。


NOTE: 您可以使用這些步驟以相同方式新增或移除link:task_defining_annotations.html["註釋"]。

.開始之前
您必須已建立查詢、以尋找所有要編輯的資產。

.步驟
. 按一下 * 瀏覽 * 並選取 * 度量查詢 * 。
+
隨即顯示「查詢」頁面。

. 按一下尋找資產的查詢名稱。
+
隨即顯示與查詢相關的資產清單。

. 在清單中選取所需的資產、或按一下頂端的核取方塊以選取「All（全部）」。
+
此時會顯示「大量動作」下拉式清單。

. 若要將應用程式新增至選取的資產、請按一下大量動作、然後選取 * 新增應用程式 * 。
. 選取一或多個應用程式。
+
您可以為主機、內部磁碟區、qtree和虛擬機器選取多個應用程式、不過、 您只能為一個磁碟區或共享區選取一個應用程式。

. 按一下「 * 儲存 * 」。
. 若要移除指派給資產的應用程式、請按一下大量動作、然後選取 * 移除應用程式 * 。
. 選取您要移除的應用程式。
. 按一下*刪除*。


您指派的任何新應用程式、都會覆寫從其他資產衍生的資產上的任何應用程式。例如、磁碟區會從主機繼承應用程式、當新的應用程式指派給磁碟區時、新的應用程式會優先於衍生的應用程式。

在大量新增或移除行動上按一下「 _Save_ 」之後、 Data Infrastructure Insights 會通知您該行動需要一些時間。您可以關閉此訊息、此動作將在背景中繼續。


NOTE: 對於具有大量相關資產的環境、將應用程式指派繼承至這些資產可能需要數分鐘的時間。如果您擁有許多相關資產、請留出更多時間進行繼承。
