---
sidebar: sidebar 
permalink: task_dc_na_solidfire.html 
summary: 配置NetApp SolidFire資料收集器 
keywords: data collector, queries, create 
---
= NetApp SolidFire全快閃陣列資料收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetApp SolidFire全快閃陣列資料收集器支援從 iSCSI 和光纖通道SolidFire配置進行庫存和效能收集。

SolidFire資料收集器利用SolidFire REST API。資料收集器所在的採集單元需要能夠啟動與SolidFire叢集管理 IP 位址上的 TCP 連接埠 443 的 HTTPS 連線。資料收集器需要能夠在SolidFire叢集上進行 REST API 查詢的憑證。



== 術語

Data Infrastructure Insights從NetApp SolidFire All-Flash 陣列資料收集器取得下列庫存資訊。對於Data Infrastructure Insights取得的每種資產類型，都會顯示用於該資產的最常用術語。當查看或排除此資料收集器的故障時，請記住以下術語：

[cols="2*"]
|===
| 供應商/型號術語 | Data Infrastructure Insights術語 


| 駕駛 | 磁碟 


| 簇 | 儲存 


| 節點 | 儲存節點 


| 體積 | 體積 


| 光纖通道連接埠 | 港口 


| 卷訪問群組、LUN 分配 | 體積圖 


| iSCSI 會話 | 體積遮罩 
|===
注意：這些只是常見的術語映射，可能並不代表此資料收集器的所有情況。



== 要求

以下是配置此資料收集器的要求：

* 管理虛擬 IP 位址
* 只讀使用者名稱和憑證
* 埠 443




== 配置

[cols="2*"]
|===
| 場地 | 描述 


| 管理虛擬 IP 位址 (MVIP) | SolidFire叢集的管理虛擬 IP 位址 


| 使用者名稱 | 用於登入SolidFire集群的名稱 


| 密碼 | 用於登入SolidFire集群的密碼 
|===


== 進階配置

[cols="2*"]
|===
| 場地 | 描述 


| 連接類型 | 選擇連線類型 


| 通訊埠 | 用於NetApp API 的連接埠 


| 庫存輪詢間隔（分鐘） | 預設為 20 分鐘 


| 效能輪詢間隔（秒） | 預設值為 300 秒 
|===


== 故障排除

當SolidFire報告錯誤時，它會在Data Infrastructure Insights中顯示如下：

_嘗試檢索資料時收到來自SolidFire設備的錯誤訊息。呼叫的是 <method> (<parameterString> )。設備發出的錯誤訊息是（檢查設備手冊）：<message>_

在哪裡：

* <method> 是一種 HTTP 方法，例如 GET 或 PUT。
* <parameterString> 是 REST 呼叫中包含的參數的逗號分隔清單。
* <message> 是裝置傳回的錯誤訊息。


關於此數據收集器的更多信息，請參閱link:concept_requesting_support.html["支援"]頁面或在link:reference_data_collector_support_matrix.html["數據收集器支援矩陣"]。
