---
sidebar: sidebar 
permalink: task_dc_emc_recoverpoint.html 
keywords: data collector, RecoverPoint, EMC, DELL 
summary: 配置 DELL EMC RecoverPoint 資料收集器。 
---
= Dell EMC RecoverPoint 資料收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
EMC RecoverPoint 資料收集器的主要用例是發現 RecoverPoint 儲存裝置所促進的捲到磁碟區的複製關係。該收集器還將發現 Recoverpoint 設備本身。請注意，Dell/EMC 銷售適用於虛擬機器的 VMware 備份解決方案——“RecoverPoint for VMs”，但該收集器不支援該解決方案

為了進行配置，資料收集器需要儲存處理器的 IP 位址以及只讀使用者名稱和密碼。

EMC RecoverPoint 資料收集器收集 RecoverPoint 在其他儲存陣列之間協調的捲到磁碟區的複製關係。Data Infrastructure Insights顯示每個 RecoverPoint 叢集的儲存陣列，並收集該叢集上的節點和儲存連接埠的庫存資料。未收集任何儲存池或磁碟區資料。



== 要求

配置此數據收集器需要以下資訊：

* 儲存處理器的 IP 位址或完全限定域名
* 只讀使用者名稱和密碼
* 透過連接埠 443 存取 REST API




== 配置

[cols="2*"]
|===
| 場地 | 描述 


| RecoverPoint 位址 | RecoverPoint 叢集的 IP 位址或完全限定域名 


| 使用者名稱 | RecoverPoint 叢集的使用者名稱 


| 密碼 | RecoverPoint 叢集使用的密碼 
|===


== 進階配置

[cols="2*"]
|===
| 場地 | 描述 


| TCP 連接埠 | 用於連接 Recoverpoint 叢集的 TCP 連接埠 


| 庫存輪詢間隔（分鐘） | 庫存調查之間的間隔。預設值為 20 分鐘。 


| 排除的集群 | 輪詢時要排除的叢集 ID 或名稱的逗號分隔清單。 
|===


== 故障排除

關於此數據收集器的更多信息，請參閱link:concept_requesting_support.html["支援"]頁面或在link:reference_data_collector_support_matrix.html["數據收集器支援矩陣"]。
