---
sidebar: sidebar 
permalink: task_dc_ibm_cleversafe.html 
keywords: data collector, IBM Cleversafe 
summary: 配置 IBM Cleversafe 資料收集器。 
---
= IBM Cleversafe 資料收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights使用此資料收集器來發現 IBM Cleversafe 儲存系統的庫存和效能資料。


NOTE: IBM Cleversafe 依照不同的原始 TB 與託管單位費率進行計量。每 40 TB 未格式化的 IBM Cleversafe 容量按 1link:concept_subscribing_to_cloud_insights.html#pricing["管理單元（MU）"] 。



== 術語

Data Infrastructure Insights從 IBM Cleversafe 資料收集器取得以下庫存資訊。對於Data Infrastructure Insights取得的每種資產類型，都會顯示用於該資產的最常用術語。當查看或排除此資料收集器的故障時，請記住以下術語：

[cols="2*"]
|===
| 供應商/型號術語 | Data Infrastructure Insights術語 


| 儲存池 | 儲存池 


| 容器 | 內部體積 


| 容器 | 文件共享 


| NFS 分享 | 分享 
|===
注意：這些只是常見的術語映射，可能並不代表此資料收集器的所有情況。



== 要求

* 叢集的外部資料服務 IP 位址
* 管理員使用者名稱和密碼
* 埠 9440




== 配置

[cols="2*"]
|===
| 場地 | 描述 


| 管理器 IP 或主機名 | 管理節點的 IP 位址或主機名 


| 使用者名稱 | 具有超級使用者或系統管理員角色的使用者帳戶的使用者名稱 


| 密碼 | 具有超級使用者或系統管理員角色的使用者帳戶的密碼 
|===


== 進階配置

[cols="2*"]
|===
| 場地 | 描述 


| 庫存輪詢間隔（分鐘） | 庫存調查之間的間隔。 


| HTTP 連線逾時（秒） | HTTP 逾時（秒）。 
|===


== 故障排除

關於此數據收集器的更多信息，請參閱link:concept_requesting_support.html["支援"]頁面或在link:reference_data_collector_support_matrix.html["數據收集器支援矩陣"]。
