---
sidebar: sidebar 
permalink: task_dc_ibm_svc.html 
keywords: IBM, SVC,SAN 
summary: 配置 IBM SAN Volume Controller 資料收集器。 
---
= 配置 IBM SAN Volume Controller 資料收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
IBM SAN Volume Controller (SVC) 數據收集器使用 SSH 收集庫存和效能數據，支援運行 SVC 作業系統的各種設備。

支援的設備清單包括 SVC、v7000、v5000 和 v3700 等型號。請參閱Data Infrastructure Insights支援矩陣以了解支援的型號和韌體版本。



== 術語

Data Infrastructure Insights從 IBM SVC 資料收集器取得以下庫存資訊。對於Data Infrastructure Insights取得的每種資產類型，都會顯示用於該資產的最常用術語。當查看或排除此資料收集器的故障時，請記住以下術語：

[cols="2*"]
|===
| 供應商/型號術語 | Data Infrastructure Insights術語 


| 駕駛 | 磁碟 


| 簇 | 儲存 


| 節點 | 儲存節點 


| Mdisk集團 | 儲存池 


| 虛擬磁碟 | 體積 


| 磁碟 | 後端 LUN 和路徑 
|===
注意：這些只是常見的術語映射，可能並不代表此資料收集器的所有情況。



=== 庫存需求

* 每個SVC叢集的IP位址
* 連接埠 22 可用
* 只讀使用者名稱和密碼




=== 性能要求

* SVC 控制台，對於任何 SVC 叢集都是必需的，並且是 SVC 發現基礎包所必需的。
* 憑證僅需要管理存取等級才能將效能檔案從叢集節點複製到設定節點。
* 透過 SSH 連接到 SVC 叢集並執行以下命令啟用資料收集：_svctask startstats -interval 1_
+
注意：或者，使用 SVC 管理使用者介面啟用資料收集。





== 配置

[cols="2*"]
|===
| 場地 | 描述 


| 叢集 IP 位址 | SVC 儲存的 IP 位址或完全限定域名 


| 庫存用戶名 | SVC CLI 的用戶名 


| 庫存密碼 | SVC CLI 的密碼 
|===


== 進階配置

[cols="2*"]
|===
| 場地 | 描述 


| 庫存輪詢間隔（分鐘） | 庫存調查之間的間隔。預設值為 40 分鐘。 


| 效能輪詢間隔（秒） | 效能輪詢之間的間隔。預設值為 300 秒。 


| 清理轉儲的統計文件 | 選取此複選框可清理轉儲的統計文件 
|===


== 故障排除

如果您在使用此資料收集器時遇到問題，請嘗試以下操作：

[cols="2*"]
|===
| 問題： | 試試一下： 


| 錯誤：“無法啟動該命令，因為它未在配置節點上運行。” | 該命令必須在配置節點上執行。 
|===
如果您在使用此資料收集器時遇到問題，請嘗試以下操作：

[cols="2*"]
|===
| 問題： | 試試一下： 


| 錯誤：“無法啟動該命令，因為它未在配置節點上運行。” | 該命令必須在配置節點上執行。 
|===
關於此數據收集器的更多信息，請參閱link:concept_requesting_support.html["支援"]頁面或在link:reference_data_collector_support_matrix.html["數據收集器支援矩陣"]。
