---
sidebar: sidebar 
permalink: task_view_configured_data_collectors.html 
keywords: acquisition, AU, data collector, collector, bulk edit, postpone polling, resume polling 
summary: 摘要。 
---
= 管理已配置的資料收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
「已安裝的資料收集器」頁面提供已為Data Infrastructure Insights配置的資料收集器的存取。您可以使用此頁面修改現有的資料收集器。

.步驟
. 在“Data Infrastructure Insights”功能表中，按一下“可觀察性”>“收集器”
+
將顯示「可用資料收集器」畫面。

. 點選*已安裝的資料收集器*
+
顯示所有已安裝的資料收集器的清單。此清單提供收集器名稱、狀態、收集器正在存取的 IP 位址以及上次從裝置取得資料的時間。可以在此畫面上執行的操作包括：

+
** 控制輪詢
** 變更資料收集器憑證
** 克隆資料收集器






== 控制資料收集器輪詢

對資料收集器進行更改後，您可能希望它立即輪詢以檢查您的更改，或者您可能希望在解決問題時將資料收集器上的資料收集推遲一天、三天或五天。

.步驟
. 在“Data Infrastructure Insights”功能表中，按一下“可觀察性”>“收集器”
. 點選*已安裝的資料收集器*
. 選取要變更的資料收集器左側的複選框
. 按一下“批次操作”並選擇要採取的投票操作。
+
可以在多個資料收集器上同時執行批次操作。選擇資料收集器，然後從*批次操作*選單中選擇要執行的操作。





== 編輯資料收集器信息

您可以編輯現有的資料收集器設定資訊。

.若要編輯單一資料收集器：
. 在Data Infrastructure Insights選單中，按一下*可觀察性>收集器*以開啟已安裝的資料收集器清單。
. 在要修改的資料收集器右側的選項功能表中，按一下*編輯*。
+
將開啟“編輯收集器”對話框。

. 輸入變更並點擊*測試配置*以測試新配置或點擊*儲存*以儲存配置。


您也可以編輯多個資料收集器：

. 選取要變更的每個資料收集器左側的核取方塊。
. 點擊“批次操作”按鈕並選擇“編輯”以開啟“編輯資料收集器”對話方塊。
. 依上述方法修改字段。
+

NOTE: 所選數據採集器必須是同一供應商和型號，並且位於同一採集單元上。

+
編輯多個資料收集器時，資料收集器名稱欄位顯示「混合」且無法編輯。其他欄位（如使用者名稱和密碼）顯示“混合”並且可以編輯。在選定的資料收集器中共用相同值的欄位顯示目前值並且可以編輯。

+
編輯多個資料收集器時，*測試配置*按鈕不可用。





== 克隆資料收集器

使用複製功能，您可以快速新增具有與另一個資料來源相同的憑證和屬性的資料來源。克隆可讓您輕鬆配置相同設備類型的多個實例。

.步驟
. 在Data Infrastructure Insights選單中，點擊*可觀察性>收集器*。
. 點選*已安裝的資料收集器*。
. 按一下要複製的資料收集器左側的複選框。
. 在所選資料收集器右側的選項選單中，按一下*克隆*。
+
將顯示“克隆資料收集器”對話框。

. 在必填欄位中輸入新資訊。
. 點選“儲存”。


.完成後
克隆操作複製所有其他屬性和設定以建立新的資料收集器。



== 對資料收集器執行批次操作

您可以同時為多個資料收集器編輯一些資訊。此功能可讓您在多個資料收集器上發起輪詢、延遲輪詢和恢復輪詢。此外，您還可以刪除多個資料收集器。

.步驟
. 在“Data Infrastructure Insights”功能表中，按一下“可觀察性”>“收集器”
. 點選*已安裝的資料收集器*
. 按一下要修改的資料收集器左側的複選框。
. 在右側的選項選單中，按一下您想要執行的選項。


.完成後
您選擇的操作在資料收集器上執行。當您選擇刪除資料收集器時，將顯示對話框，要求您確認該操作。
