---
sidebar: sidebar 
permalink: task_dc_emc_xio.html 
keywords: data collector, XtremeIO, EMC 
summary: 配置 XtremeIO 資料收集器。 
---
= Dell EMC XtremeIO 資料收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
EMC XtremIO 資料收集器從 EMC XtremIO 儲存系統取得清單和效能資料。



== 要求

若要設定 EMC XtremIO (HTTP) 資料收集器，您必須具有：

* XtremIO 管理伺服器 (XMS) 主機位址
* 具有管理員權限的帳戶
* 存取連接埠 443 (HTTPS)




== 術語

Data Infrastructure Insights從 EMC XtremIO 資料收集器取得以下清單資訊。對於Data Infrastructure Insights取得的每種資產類型，都會顯示用於該資產的最常用術語。查看或排除此資料來源故障時，請記住以下術語：

[cols="2*"]
|===
| 供應商/型號術語 | Data Infrastructure Insights術語 


| 磁碟（SSD） | 磁碟 


| 簇 | 儲存 


| 控制器 | 儲存節點 


| 體積 | 體積 


| LUN 映射 | 體積圖 


| 目標 FC 發起者 | 體積遮罩 
|===
注意：這些只是常用術語映射，可能並不代表此資料來源的所有情況。



== 要求

* XtremIO 管理伺服器 (XMS) 主機 IP 位址
* XtremIO 的管理員使用者名稱和密碼




== 配置

[cols="2*"]
|===
| 場地 | 描述 


| XMS 主機 | XtremIO 管理伺服器的 IP 位址或完全限定域名 


| 使用者名稱 | XtremIO 管理伺服器的使用者名 


| 密碼 | XtremIO 管理伺服器的密碼 
|===


== 進階配置

[cols="2*"]
|===
| 場地 | 描述 


| TCP 連接埠 | 用於連接 XTremIO 管理伺服器的 TCP 連接埠。預設值為 443。 


| 庫存輪詢間隔（分鐘） | 庫存調查之間的間隔。預設值為 60 分鐘。 


| 效能輪詢間隔（秒） | 效能輪詢之間的間隔。預設值為 300 秒。 
|===


== 故障排除

關於此數據收集器的更多信息，請參閱link:concept_requesting_support.html["支援"]頁面或在link:reference_data_collector_support_matrix.html["數據收集器支援矩陣"]。
