---
sidebar: sidebar 
permalink: task_dc_emc_vnx_file.html 
keywords: data collector, Celerra, EMC, DELL, VNX File 
summary: 配置 DELL EMC Celerra 資料收集器。 
---
= DELL EMC VNX File（以前稱為 Celerra 統一儲存系統）資料收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
此資料收集器從 VNX 檔案儲存系統取得庫存資訊。為了進行配置，此資料收集器需要儲存處理器的 IP 位址以及唯讀使用者名稱和密碼。



== 術語

Data Infrastructure Insights從 VNX 檔案資料收集器取得以下清單資訊。對於Data Infrastructure Insights取得的每種資產類型，都會顯示用於該資產的最常用術語。當查看或排除此資料收集器的故障時，請記住以下術語：

[cols="2*"]
|===
| 供應商/型號術語 | Data Infrastructure Insights術語 


| Celerra 網路伺服器/Celerra 儲存池 | 儲存池 


| 檔案系統 | 內部體積 


| 資料移動器 | 控制器 


| 數據移動器上安裝的檔案系統 | 文件共享 


| CIFS 和 NFS 導出 | 分享 


| 磁碟卷 | 後端 LUN 
|===
注意：這些只是常見的術語映射，可能並不代表此資料收集器的所有情況。



== 要求

您需要以下內容來設定此資料收集器：

* 儲存處理器的 IP 位址
* 只讀使用者名稱和密碼
* SSH 連接埠 22




== 配置

[cols="2*"]
|===
| 場地 | 描述 


| VNX 檔案 IP 位址 | VNX File 設備的 IP 位址或完全限定域名 


| 使用者名稱 | 用於登入 VNX File 設備的名稱 


| 密碼 | 用於登入 VNX File 設備的密碼 
|===


== 進階配置

[cols="2*"]
|===
| 場地 | 描述 


| 庫存輪詢間隔（分鐘） | 庫存調查之間的間隔。預設值為 20 分鐘。 
|===


== 故障排除

如果您在使用此資料收集器時遇到問題，請嘗試以下操作：



=== 存貨

[cols="2*"]
|===
| 問題： | 試試一下： 


| 錯誤：DART 更新正在進行中，無法繼續 | 可能的解決方案：暫停資料收集器並等待 DART 升級完成後再嘗試另一個採集請求。 
|===
更多資訊可從link:concept_requesting_support.html["支援"]頁面或在link:reference_data_collector_support_matrix.html["數據收集器支援矩陣"]。
