---
sidebar: sidebar 
permalink: task_create_annotation.html 
keywords: annotations, annotation rules, manual annotations, 
summary: 如何建立註釋。 
---
= 使用註釋
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您建立註釋並將其指派給您監控的資產。註釋是提供有關資產資訊的說明，例如實體位置、使用壽命、儲存層或磁碟區服務等級。



== 定義註釋

使用註釋，您可以為資產新增符合您的業務需求的自訂業務特定資料。雖然Data Infrastructure Insights提供了一組預設註釋，例如資產生命週期（生日或壽命終止）、建築物或資料中心位置和層級，但您可能會發現您想以其他方式查看資料。

自訂註釋中的數據補充了已經收集的設備數據，例如交換器製造商、連接埠數量和效能統計數據。您使用註釋添加的資料不會被Data Infrastructure Insights發現。

.開始之前
* 列出必須與環境資料關聯的任何行業術語。
* 列出必須與環境資料關聯的公司術語。
* 確定您可能使用的任何預設註釋類型。
* 確定您需要建立哪些自訂註釋。您需要先建立註釋，然後才能將其指派給資產。


使用以下步驟建立註解。

.步驟
. 在Data Infrastructure Insights選單中，點擊“可觀察性”>“豐富”>“註釋”
. 按一下「*+ 註釋*」以建立新註釋。
. 輸入新註釋的名稱、描述和類型。
+
例如，輸入以下內容來建立定義資料中心 4 中資產的實體位置的文字註解：

+
** 輸入註釋的名稱，例如“位置”
** 輸入註釋內容的描述，例如“實體位置是資料中心 4”
** 輸入註釋的“類型”，例如“文字”。






== 手動為資產分配註釋

為資產分配註釋可以幫助您以與您的業務相關的方式對資產進行排序、分組和報告。雖然您可以使用註釋規則自動將註釋指派給特定類型的資產，但您可以使用資產頁面將註釋指派給單一資產。

.開始之前
* 您必須已經建立了要指派的註釋。


.步驟
. 登入您的Data Infrastructure Insights環境。
. 尋找要套用註釋的資產。
+
** 您可以透過查詢、從儀表板小工具中選擇或搜尋來定位資產。找到所需的資產後，按一下連結即可開啟該資產的登入頁面。


. 在資產頁面的使用者資料部分中，按一下 *+ 註釋*。
. 將顯示「新增註解」對話方塊。
. 從清單中選擇一個註釋。
. 按一下“值”並根據所選註釋的類型執行以下操作之一：
+
** 如果註釋類型是清單、日期或布林值，請從清單中選擇一個值。
** 如果註釋類型是文本，請輸入一個值。


. 點選“儲存”。


如果在指派註解後想要變更其值，請按一下註解欄位並選擇其他值。如果註解是清單類型，並且選擇了「動態新增值」選項，則除了選擇現有值之外，還可以鍵入新值。



== 使用註釋規則指派註釋

若要根據您定義的標準自動將註解指派給資產，請配置註解規則。Data Infrastructure Insights根據這些規則將註釋分配給資產。  Data Infrastructure Insights還提供了兩個預設註解規則，您可以根據需要修改它們，如果不想使用它們，則可以刪除它們。



=== 建立註解規則

作為手動將註釋應用於單一資產的替代方法，您可以使用註釋規則自動將註釋套用至多個資產。當 Insight 評估註釋規則時，在單一資產頁面上手動設定的註釋優先於基於規則的註釋。

.開始之前
您必須已經為註釋規則建立了查詢。

.關於此任務
雖然您可以在建立規則時編輯註解類型，但您應該提前定義類型。

.步驟
. 點選*管理>註解規則*
+
註釋規則頁面顯示現有註釋規則的清單。

. 按一下“*+ 新增*”。
. 執行以下操作：
+
.. 在「*名稱*」方塊中，輸入描述規則的唯一名稱。
+
該名稱將出現在註解規則頁面中。

.. 點擊“*查詢*”並選擇用於將註釋應用於資產的查詢。
.. 點擊*註釋*並選擇要套用的註解。
.. 點擊“*值*”並為註釋選擇一個值。
+
例如，如果您選擇生日作為註釋，則您可以為該值指定一個日期。

.. 點選“儲存”
.. 如果您想立即執行所有規則，請按一下「執行所有規則」；否則，規則將按照定期安排的時間間隔運行。



