---
sidebar: sidebar 
permalink: task_create_annotation_rules.html 
summary: 您可以建立附註規則、自動將附註套用至多個資產。 
keywords: annotate, annotation, rules 
---
= 建立註釋規則
:hardbreaks:
:allow-uri-read: 


[role="lead"]
您可以使用註釋規則、根據您定義的準則、自動將註釋套用至多個資產。Data Infrastructure Insights 會根據這些規則將註釋指派給資產。Cloud Insight評估附註規則時、在個別資產頁面上手動設定的附註優先於規則型附註。

.開始之前
您必須已建立註釋規則的查詢。

.步驟
. 在 Data Infrastructure Insights 功能表中、按一下 * 管理 > 附註規則 * 。
. 按一下「*+規則*」以新增註釋規則。
+
此時會顯示「新增規則」對話方塊。

. 請執行下列動作：
+
.. 在*名稱*方塊中、輸入描述規則的唯一名稱。
+
名稱會出現在「附註規則」頁面中。

.. 按一下 * 查詢 * 、然後選取 Data Infrastructure Insights 用來識別註釋所套用資產的查詢。
.. 按一下*註釋*、然後選取您要套用的註釋。
.. 按一下*值*、然後選取註釋的值。
+
例如、如果您選擇「Birthday」做為註釋、則需指定值的日期。

.. 按一下「*儲存*」
.. 如果您要立即執行所有規則、請按一下*執行所有規則*；否則、規則會以定期排程的時間間隔執行。
+

NOTE: 在大型 Data Infrastructure Insights 環境中、您可能會發現執行註釋規則似乎需要一段時間才能完成。這是因為索引程式會先執行、而且必須在執行規則之前完成。索引器可讓 Data Infrastructure Insights 在資料中搜尋或篩選新的或更新的物件和計數器。規則引擎會等到索引程式完成更新後再套用規則。







== 修改註釋規則

您可以修改附註規則、以變更規則名稱、其附註、附註值或與規則相關的查詢。

.步驟
. 在 Data Infrastructure Insights 功能表中、按一下 * 管理 > 附註規則 * 。
+
「附註規則」頁面會顯示現有附註規則的清單。

. 找出您要修改的註釋規則。
+
您可以在篩選方塊中輸入值來篩選註釋規則、或按一下頁碼來逐頁瀏覽註釋規則。

. 按一下您要修改之規則的功能表圖示。
. 按一下*編輯*
+
隨即顯示「編輯規則」對話方塊。

. 修改註釋規則的名稱、註釋、值或查詢。




== 變更規則順序

註釋規則會從規則清單頂端到底部進行處理。若要變更規則的處理順序、請執行下列步驟：

.步驟
. 按一下您要移動之規則的功能表圖示。
. 視需要按*上移*或*下移*、直到規則出現在您要的位置。


請注意、當在資產上執行多個更新相同評註的規則時、第一個規則（從上而下執行）會套用評註並更新資產、然後套用第二個規則、但不會變更先前規則所設定的任何評註。



== 刪除註釋規則

您可能想要刪除不再使用的註釋規則。

.步驟
. 在 Data Infrastructure Insights 功能表中、按一下 * 管理 > 附註規則 * 。
+
「附註規則」頁面會顯示現有附註規則的清單。

. 找出您要刪除的註釋規則。
+
您可以在篩選方塊中輸入值來篩選註釋規則、或按一下頁碼來逐頁瀏覽註釋規則。

. 按一下您要刪除之規則的功能表圖示。
. 按一下*刪除*
+
隨即顯示確認訊息、提示您是否要刪除規則。

. 按一下「*確定*」

