---
sidebar: sidebar 
permalink: task_dc_ms_hyperv.html 
keywords: data collector, Microsoft, Hyper-V 
summary: 配置 Microsoft Hyper-V 資料收集器。 
---
= Microsoft Hyper-V 資料收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Microsoft Hyper-V 資料收集器從虛擬化伺服器運算環境中取得庫存和效能資料。此資料收集器可以發現獨立的 Hyper-V 主機或整個叢集 - 每個獨立主機或叢集建立一個收集器。



== 術語

Data Infrastructure Insights從 Microsoft Hyper-V (WMI) 取得以下庫存資訊。對於Data Infrastructure Insights取得的每種資產類型，都會顯示用於該資產的最常用術語。當查看或排除此資料收集器的故障時，請記住以下術語：

[cols="2*"]
|===
| 供應商/型號術語 | Data Infrastructure Insights術語 


| 虛擬硬碟 | 虛擬磁碟 


| 主持人 | 主持人 


| 虛擬機 | 虛擬機 


| 叢集共享卷（CSV）、分區卷 | 資料儲存 


| 網際網路 SCSI 設備，多路徑 SCSI LUN | 邏輯單元號 


| 光纖通道連接埠 | 港口 
|===
注意：這些只是常見的術語映射，可能並不代表此資料收集器的所有情況。



== 要求

配置此資料收集器需要以下內容：

* Hyper-V 需要開啟連接埠 5985 以進行資料收集和遠端存取/管理。
* 叢集或獨立虛擬機器管理程式的 IP 位址或 FQDN。與將收集器指向叢集中某個特定節點相比，使用浮動叢集主機名稱或 IP 可能是最可靠的方法。
* 可在叢集中的所有虛擬機器管理程式上執行的管理層級使用者帳戶。
* WinRM 需要在所有虛擬機器管理程式上啟用並監聽
* 連接埠需求：透過 WMI 和動態 TCP 連接埠指派的連接埠 135 對於 Windows 2003 及更早版本為 1024-65535，對於 Windows 2008 為 49152-65535。
* DNS 解析必須成功，即使資料收集器僅指向 IP 位址
* 每個 Hyper-V 虛擬機器管理程式必須為每個主機上的每個 VM 啟用「資源計量」。這使得每個虛擬機器管理程式可以為每個客戶機上的Data Infrastructure Insights提供更多資料。如果未設置，則每個客戶獲取的效能指標會更少。有關資源計量的更多信息，請參閱 Microsoft 文件：
+
link:https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh831661(v=ws.11)["Hyper-V 資源計量概述"]

+
link:https://docs.microsoft.com/en-us/powershell/module/hyper-v/enable-vmresourcemetering?view=win10-ps["啟用-VMResourceMetering"]




NOTE: Hyper-V 資料收集器需要 Windows 擷取單元。



== 配置

[cols="2*"]
|===
| 場地 | 描述 


| 群集 IP 位址或浮動群集 FQDN | 叢集或獨立非叢集虛擬機器管理程式的 IP 位址或完全限定域名 


| 使用者名稱 | 虛擬機器管理程式的管理員使用者名 


| 密碼 | 虛擬機器管理程式的密碼 


| DNS 網域後綴 | 與簡單主機名稱結合以呈現虛擬機器管理程式的 FQDN 的主機名稱後綴 
|===


== 進階配置

[cols="2*"]
|===
| 場地 | 描述 


| 庫存輪詢間隔（分鐘） | 預設值為 20 分鐘。 
|===


== 故障排除

關於此數據收集器的更多信息，請參閱link:concept_requesting_support.html["支援"]頁面或在link:reference_data_collector_support_matrix.html["數據收集器支援矩陣"]。
