---
sidebar: sidebar 
permalink: task_dc_proxmox_ve.html 
keywords: data collector, Proxmox Virtual Environment, PVE 
summary: 配置 Proxmox 虛擬環境資料收集器。 
---
= Proxmox Virtual Environment 資料收集器
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
DII Proxmox 虛擬環境收集器將收集基於 PVE 的虛擬機器（而非 LXC 容器）和主機/虛擬機器管理程式的清單和效能資料。這是一個基於 HTTPS REST API 的收集器，需要與監聽 TCP 8006 連接埠的 pveproxy 服務/守護程式提供的 Proxmox REST API 通訊。

此資料收集器使用使用者 + 權杖驗證。您需要在每個 Proxmox 叢集上建立一個服務帳戶，並為該使用者指派對應的權限，然後產生一個具有相同權限的 API 權杖。請附註，特定 Proxmox 使用者的權杖不一定擁有與該使用者相同的權限。DII 通常需要全域稽核/監控層級的權限——如果您透過 Proxmox UI 建立服務帳戶，請將 PathPermision 的起始路徑設定為「/」，將「傳播」設定為「是」，並至少解除鎖定 Datastore Audit、Mapping Audit、Pool Audit、SDN Audit、Sys Audit、VM Audit、VM Monitor 權限。建立使用者後，即可為其建立存取權杖。強烈建議將權杖的過期時間設為 0，以確保權杖永不過期。



[[terminology]]
== 術語

對於Data Infrastructure Insights所取得的每種資產類型，都會顯示該資產最常用的術語。當查看或排除此資料收集器的故障時，請記住以下術語：

[cols="50,50"]
|===
| 供應商/型號術語 | Data Infrastructure Insights術語 


| 磁碟 | 虛擬磁碟 


| 主持人 | 主持人 


| 虛擬機 | 虛擬機 


| 儲存 | 資料儲存 
|===
注意：這些只是常見的術語映射，可能並不代表此資料收集器的所有情況。



[[configuration]]
== 配置

[cols="50,50"]
|===
| 場地 | 描述 


| 主機名稱或 IP 位址 | 儲存系統的主機名稱 IP 位址 


| API 權杖 ID | 存取需要 API 令牌 


| API Token 秘密金鑰 | 上述令牌的秘密 
|===


[[advanced-configuration]]
== 進階配置

[cols="50,50"]
|===
| 場地 | 描述 


| HTTPS 通訊埠 | 用於 HTTPS 通訊的連接埠（預設 8006） 


| 庫存輪詢間隔（分鐘） | 預設值為 20 分鐘。 
|===


[[troubleshooting]]
== 故障排除

關於此數據收集器的更多信息，請參閱link:concept_requesting_support.html["支援"]頁面或在link:reference_data_collector_support_matrix.html["數據收集器支援矩陣"]。
