---
sidebar: sidebar 
permalink: task_business_entity_annotations.html 
keywords: annotations, business entity 
summary: 業務實體註釋可用於監控和報告業務層級結構中的資產 
---
= 業務實體註釋
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用*業務實體*註解類型為您的公司環境建立和管理業務實體。



== 建立商業實體

若要建立業務實體，請執行下列操作：

. 按一下*管理>註解*，然後按一下_業務實體_連結。
+
顯示目前定義的業務實體清單。

. 按一下“*+ 商業實體*”。
. 輸入「*租戶*」、「*業務線*」、「業務部門*」和「*專案*」欄位的值。
+
如果任何欄位不適用於您的企業實體，您可以將該欄位留空。

. 如果您之前已為某個欄位輸入了值，則可以從下拉式選單中選擇該值。您不需要再次輸入。



NOTE: 選定的值必須組成唯一的總體業務實體。例如，如果您已經有一個依序具有值 _A / B / C / D_ 的業務實體，則您無法依該順序建立具有這些值的另一個業務實體。但是，您可以按照不同的順序建立具有這些值的業務實體。



== 將業務實體應用於對象

將業務實體應用於一個或多個物件的最簡單方法是透過查詢。

. 按一下*查詢>+新查詢*並選擇所需的物件類型。您可以套用篩選器來進一步縮小結果範圍。
. 按一下核取方塊以選擇您想要套用業務實體的物件。
. 點擊*批次操作*並選擇*新增註解*。
. 選擇_Business Entity_註釋，然後從清單中選擇所需的業務實體值。
. 按一下「*儲存*」將業務實體套用到物件。


您也可以透過導覽至物件的資產登入頁面並點擊「使用者資料」部分中的「*+註釋」）將業務實體套用至單一物件。

您也可以配置link:task_create_annotation_rules.html["註釋規則"]將業務實體應用於對象。


NOTE: 一個物件只能有一個與之關聯的業務實體。



== 從物件中刪除業務實體

若要從一個或多個對像中刪除業務實體，請查詢並選擇對象，按一下*批次操作*並選擇_刪除註釋_。選擇業務實體註解並點擊*刪除*。
