---
sidebar: sidebar 
permalink: task_dc_na_storagegrid.html 
summary: 配置NetApp StorageGRID資料收集器 
keywords: data collector, queries, create, storagegrid 
---
= NetApp StorageGRID資料收集器
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp StorageGRID資料收集器支援從StorageGRID配置收集庫存和效能。

[NOTE]
====
為了在所有StorageGRID系統中對 DII 權利進行一致的計量，無論底層硬體拓撲和配置如何， Data Infrastructure Insights都會使用總可用容量（storagegrid_storage_utilization_total_space_bytes），而不是基於實體磁碟佈局的 RAW 容量。

對於使用基於容量的授權模式的客戶， StorageGRID被計量為「物件」儲存。

對於使用傳統 (MU) 授權模式的客戶， StorageGRID以 40TiB 比 1 MU 的比率計量為二級儲存。

====


== 術語

Data Infrastructure Insights從NetApp StorageGRID收集器取得以下庫存資訊。對於所取得的每種資產類型，都會顯示用於該資產的最常用術語。當查看或排除此資料收集器的故障時，請記住以下術語：

[cols="2*"]
|===
| 供應商/型號術語 | Data Infrastructure Insights術語 


| StorageGRID | 儲存 


| 節點 | 節點 


| 租戶 | 儲存池 


| 桶 | 內部體積 
|===


== 要求

配置此資料來源的要求如下：

* StorageGRID主機 IP 位址
* 已指派「指標查詢」和「租用戶存取」角色的使用者的使用者名稱和密碼
* 連接埠 443（或 8443，如果已配置）




== 配置

[cols="2*"]
|===
| 場地 | 描述 


| StorageGRID主機 IP 位址 | StorageGRID （Grid Manager）的管理 IP 位址 


| 使用者名稱 | 用於登入 StorageGRID （ Grid Manager ）的名稱 


| 密碼 | 用於登入 StorageGRID （ Grid Manager ）的密碼 
|===


== 進階配置

[cols="2*"]
|===
| 場地 | 描述 


| 庫存輪詢間隔（分鐘） | 預設為 60 分鐘 


| 效能輪詢間隔（秒） | 預設值為 900 秒 
|===


== 單一登入（SSO）

這link:https://docs.netapp.com/sgws-112/index.jsp["StorageGRID"]韌體版本有對應的API版本；3.0 API及更新版本支援單一登入（SSO）。

|===


| 韌體版本 | API 版本 | 支援單一登入（SSO） 


| 11.1 | 2 | 不 


| 11.2 | 3.0 | 是的 


| 11.5 | 3.3 | 是的 
|===


== 故障排除

關於此數據收集器的更多信息，請參閱link:concept_requesting_support.html["支援"]頁面或在link:reference_data_collector_support_matrix.html["數據收集器支援矩陣"]。
