---
sidebar: sidebar 
permalink: task_dc_na_amazon_fsx.html 
keywords: 'data collector, stout, fsx, fsx-netapp, Amazon, AWS, cluster, volume, share, LUN"' 
summary: 適用於NetApp ONTAP 的Amazon FSX資料蒐集器 
---
= 適用於NetApp ONTAP 的Amazon FSX資料收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
此資料收集器會從Amazon FSX for NetApp ONTAP 獲取庫存與效能資料。此資料收集器將在 Data Infrastructure Insights 服務區域中逐步提供使用。如果您在 Data Infrastructure Insights 環境中沒有看到此收集器的圖示、請聯絡您的銷售人員。


NOTE: 此 Data Infrastructure Insights 收集器需要 ONTAP 使用者具備 _Filesystem-roculs_ 角色。請參閱 AWS link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/roles-and-users.html["角色和規則"] 文件以瞭解可用的選項。目前 AWS 只支援一種檔案系統範圍的使用者角色、即 _fsxadmin_ 。這是用於 Data Infrastructure Insights 收集器的適當角色。使用者也應該指派這三個應用程式： HTTP 、 ontapi 、 ssh 。



== 術語

Data Infrastructure Insights 會從 NetApp 資料收集器取得庫存與效能資料。對於所取得的每種資產類型、都會顯示該資產最常用的術語。檢視或疑難排解此資料收集器時、請謹記下列術語：

[cols="2*"]
|===
| 廠商/模型術語 | Data Infrastructure Insights 術語 


| 叢集 | 儲存設備 


| LUN | Volume 


| Volume | 內部Volume 
|===


== FSx-NetApp術語

以下術語適用於您在FSx-NetApp儲存資產登陸頁面上可能找到的物件或參考資料。其中許多術語也適用於其他資料收集器。



=== 儲存設備

* 模型–此叢集中唯一、獨立模型名稱的以逗號分隔的清單。
* 廠商：AWS
* 序號–陣列序號。
* IP–通常是在資料來源中設定的IP或主機名稱。
* 原始容量：指派給FSX檔案系統之所有SSD儲存設備的基礎2總和。
* 延遲：代表主機面對的工作負載在讀取和寫入過程中所經歷的情況。在理想情況下、 Data Infrastructure Insights 會直接取得這項價值、但通常情況並非如此。資料基礎架構 Insights 通常會執行從個別內部磁碟區統計資料衍生的 IOPs 加權計算、而不是提供這項功能的陣列。
* 處理量：從內部磁碟區集合而來。管理：這可能包含裝置管理介面的超連結。由 Data Infrastructure Insights 資料來源以程式設計方式建立、作為庫存報告的一部分。




=== 儲存資源池

* 儲存設備：此資源池所使用的儲存陣列。必填。
* 類型–從列舉的可能性清單清單中選取一個描述性值。最常見的是「Aggregate」或「RAID Group」。
* 容量：此處的值是已用邏輯容量、可用容量和邏輯總容量、以及這些容量使用的百分比。
* IOPS：此儲存集區上所有已配置磁碟區的IOPS總和。
* 處理量：此儲存資源池上所有已配置磁碟區的總處理量。




== 需求

以下是設定及使用此資料收集器的需求：

* 您必須具有「 fsxadmin 」角色的帳戶存取權、並指派三個應用程式： ssh 、 ontapi 、 http
* 帳戶詳細資料包括使用者名稱和密碼。
* 連接埠需求： 443




== 組態

[cols="2*"]
|===
| 欄位 | 說明 


| NetApp管理IP | NetApp叢集的IP位址或完整網域名稱 


| 使用者名稱 | NetApp叢集的使用者名稱 


| 密碼 | NetApp叢集的密碼 
|===


== 進階度量

此資料收集器會從FSXfor NetApp ONTAP Sfor Storage收集下列進階度量資料：

* fpolicy
* nfsv3
* NFSv3：節點
* nfsv4
* nfsv4_1
* NFSv1_1：節點
* NFSv4：節點
* policy_group
* qtree
* Volume
* 工作負載磁碟區


請注意、 FSX CLI 和 API 命令會擷取 Data Infrastructure Insights ZAPI 未收集的一些容量值、因此資料基礎架構 Insights 中的某些容量值（例如儲存集區的容量值）可能與 FSX 本身不同。



== 疑難排解

如果您在使用此資料收集器時遇到問題、請嘗試下列事項：



=== 庫存

[cols="2*"]
|===
| 問題： | 試用： 


| 接收401 HTTP回應或13003 ZAPI錯誤代碼、且ZAPI傳回「權限不足」或「未授權使用此命令」 | 檢查使用者名稱和密碼、以及使用者權限/權限。 


| ZAPI傳回「叢集角色不是叢集管理LIF」 | AU需要與叢集管理IP對話。檢查IP並視需要變更為不同的IP 


| ZAPI命令在重試後失敗 | AU與叢集發生通訊問題。檢查網路、連接埠號碼和IP位址。使用者也應該嘗試從AU機器的命令列執行命令。 


| AU無法透過HTTP連線至ZAPI | 檢查ZAPI連接埠是否接受純文字。如果AU嘗試傳送純文字到SSL通訊端、通訊就會失敗。 


| 通訊失敗、出現SSLException | AU正在嘗試將SSL傳送至檔案管理器上的純文字連接埠。檢查ZAPI連接埠是否接受SSL、或使用不同的連接埠。 


| 其他連線錯誤：ZAPI回應的錯誤代碼為13001、「資料庫未開啟」ZAPI錯誤代碼為60、回應包含「API未按時完成」ZAPI回應包含「initialize_session（）傳回的空環境」ZAPI錯誤代碼為14007、回應包含「節點不健全」 | 檢查網路、連接埠號碼和IP位址。使用者也應該嘗試從AU機器的命令列執行命令。 
|===
您可以在頁面或中找到其他link:concept_requesting_support.html["支援"]link:reference_data_collector_support_matrix.html["資料收集器支援對照表"]資訊。
